-- ============================================
-- SQL Query to insert 500 users to new project database
-- Generated from user_credentials.csv
-- Passwords need to be hashed using bcrypt before insertion
-- ============================================

-- This assumes your users table has the following structure:
-- id, first_name, last_name, email, job_title, company_name, country, password_hash, role, is_active, created_at

-- Note: Run the password hashing script first to generate bcrypt hashes
-- Or use the plain passwords below and hash them in your application

INSERT INTO users (first_name, last_name, email, job_title, company_name, country, password_hash, role, is_active, created_at) VALUES
('dataadmin', 'tgstechinfo', 'dataadmin@tgstechinfo.com', 'Admin', 'null', 'null', '$2a$12$placeholder_hash_for_Default@2026', 'admin', 1, NOW()),
('user123', 'gmail', 'user123@gmail.com', 'User', 'tgstechinfo', 'null', '$2a$12$placeholder_hash_for_tgstechinfo@2026', 'user', 1, NOW()),
('harper', 'gonzalez', 'harper.gonzalez30@gmail.com', 'User', '6sense Australia', 'Australia', '$2a$12$placeholder_hash_for_6senseAustralia@2026', 'user', 1, NOW()),
('jack', 'harris', 'jack.harris27@gmail.com', 'User', '6sense Australia', 'Australia', '$2a$12$placeholder_hash_for_6senseAustralia@2026', 'user', 1, NOW()),
('charlotte', 'jones', 'charlotte.jones24@hotmail.com', 'User', 'Adobe Marketo Australia', 'Australia', '$2a$12$placeholder_hash_for_AdobeMarketoAustralia@2026', 'user', 1, NOW()),
('grace', 'garcia', 'grace.garcia34@company.com', 'User', 'Adobe Marketo Australia', 'Australia', '$2a$12$placeholder_hash_for_AdobeMarketoAustralia@2026', 'user', 1, NOW()),
('henry', 'davis', 'henry.davis61@hotmail.com', 'User', 'Adobe Marketo Australia', 'Australia', '$2a$12$placeholder_hash_for_AdobeMarketoAustralia@2026', 'user', 1, NOW()),
('amelia', 'smith', 'amelia.smith65@company.com', 'User', 'Autopilot Australia', 'Australia', '$2a$12$placeholder_hash_for_AutopilotAustralia@2026', 'user', 1, NOW()),
('chloe', 'lee', 'chloe.lee68@yahoo.com', 'User', 'Autopilot Australia', 'Australia', '$2a$12$placeholder_hash_for_AutopilotAustralia@2026', 'user', 1, NOW()),
('olivia', 'lee', 'olivia.lee52@outlook.com', 'User', 'Autopilot Australia', 'Australia', '$2a$12$placeholder_hash_for_AutopilotAustralia@2026', 'user', 1, NOW()),
('sienna', 'walker', 'sienna.walker60@outlook.com', 'User', 'Bombora Australia', 'Australia', '$2a$12$placeholder_hash_for_BomboraAustralia@2026', 'user', 1, NOW()),
('evelyn', 'martinez', 'evelyn.martinez42@yahoo.com', 'User', 'Clearbit Australia', 'Australia', '$2a$12$placeholder_hash_for_ClearbitAustralia@2026', 'user', 1, NOW()),
('harper', 'garcia', 'harper.garcia13@outlook.com', 'User', 'Clearbit Australia', 'Australia', '$2a$12$placeholder_hash_for_ClearbitAustralia@2026', 'user', 1, NOW()),
('harper', 'jackson', 'harper.jackson69@outlook.com', 'User', 'Clearbit Australia', 'Australia', '$2a$12$placeholder_hash_for_ClearbitAustralia@2026', 'user', 1, NOW()),
('lucas', 'thomas', 'lucas.thomas50@company.com', 'User', 'Clearbit Australia', 'Australia', '$2a$12$placeholder_hash_for_ClearbitAustralia@2026', 'user', 1, NOW()),
('grace', 'miller', 'grace.miller59@company.com', 'User', 'Demandbase Australia', 'Australia', '$2a$12$placeholder_hash_for_DemandbaseAustralia@2026', 'user', 1, NOW()),
('olivia', 'rodriguez', 'olivia.rodriguez17@gmail.com', 'User', 'Demandbase Australia', 'Australia', '$2a$12$placeholder_hash_for_DemandbaseAustralia@2026', 'user', 1, NOW()),
('zoe', 'wilson', 'zoe.wilson3@yahoo.com', 'User', 'Demandbase Australia', 'Australia', '$2a$12$placeholder_hash_for_DemandbaseAustralia@2026', 'user', 1, NOW()),
('chloe', 'williams', 'chloe.williams16@outlook.com', 'User', 'Drip Australia', 'Australia', '$2a$12$placeholder_hash_for_DripAustralia@2026', 'user', 1, NOW()),
('emily', 'martinez', 'emily.martinez56@yahoo.com', 'User', 'Drip Australia', 'Australia', '$2a$12$placeholder_hash_for_DripAustralia@2026', 'user', 1, NOW()),
('harper', 'taylor', 'harper.taylor1@hotmail.com', 'User', 'Drip Australia', 'Australia', '$2a$12$placeholder_hash_for_DripAustralia@2026', 'user', 1, NOW()),
('liam', 'lee', 'liam.lee43@yahoo.com', 'User', 'Drip Australia', 'Australia', '$2a$12$placeholder_hash_for_DripAustralia@2026', 'user', 1, NOW()),
('mia', 'harris', 'mia.harris39@outlook.com', 'User', 'Drip Australia', 'Australia', '$2a$12$placeholder_hash_for_DripAustralia@2026', 'user', 1, NOW()),
('william', 'gonzalez', 'william.gonzalez11@gmail.com', 'User', 'Drip Australia', 'Australia', '$2a$12$placeholder_hash_for_DripAustralia@2026', 'user', 1, NOW()),
('zoe', 'jones', 'zoe.jones64@yahoo.com', 'User', 'Drip Australia', 'Australia', '$2a$12$placeholder_hash_for_DripAustralia@2026', 'user', 1, NOW()),
('ivy', 'davis', 'ivy.davis72@outlook.com', 'User', 'Dun & Bradstreet Australia', 'Australia', '$2a$12$placeholder_hash_for_Dun&BradstreetAustralia@2026', 'user', 1, NOW()),
('millie', 'thompson', 'millie.thompson40@outlook.com', 'User', 'Dun & Bradstreet Australia', 'Australia', '$2a$12$placeholder_hash_for_Dun&BradstreetAustralia@2026', 'user', 1, NOW()),
('harper', 'jackson', 'harper.jackson36@company.com', 'User', 'Eloqua Australia', 'Australia', '$2a$12$placeholder_hash_for_EloquaAustralia@2026', 'user', 1, NOW()),
('harper', 'miller', 'harper.miller48@gmail.com', 'User', 'Eloqua Australia', 'Australia', '$2a$12$placeholder_hash_for_EloquaAustralia@2026', 'user', 1, NOW()),
('henry', 'robinson', 'henry.robinson51@company.com', 'User', 'Eloqua Australia', 'Australia', '$2a$12$placeholder_hash_for_EloquaAustralia@2026', 'user', 1, NOW()),
('lily', 'garcia', 'lily.garcia38@yahoo.com', 'User', 'Eloqua Australia', 'Australia', '$2a$12$placeholder_hash_for_EloquaAustralia@2026', 'user', 1, NOW()),
('ruby', 'thomas', 'ruby.thomas4@outlook.com', 'User', 'Eloqua Australia', 'Australia', '$2a$12$placeholder_hash_for_EloquaAustralia@2026', 'user', 1, NOW()),
('sophia', 'davis', 'sophia.davis22@yahoo.com', 'User', 'Eloqua Australia', 'Australia', '$2a$12$placeholder_hash_for_EloquaAustralia@2026', 'user', 1, NOW()),
('william', 'anderson', 'william.anderson76@yahoo.com', 'User', 'Eloqua Australia', 'Australia', '$2a$12$placeholder_hash_for_EloquaAustralia@2026', 'user', 1, NOW()),
('evelyn', 'davis', 'evelyn.davis58@hotmail.com', 'User', 'Freshworks Australia', 'Australia', '$2a$12$placeholder_hash_for_FreshworksAustralia@2026', 'user', 1, NOW()),
('william', 'martinez', 'william.martinez2@yahoo.com', 'User', 'Freshworks Australia', 'Australia', '$2a$12$placeholder_hash_for_FreshworksAustralia@2026', 'user', 1, NOW()),
('chloe', 'martinez', 'chloe.martinez25@hotmail.com', 'User', 'HubSpot Australia', 'Australia', '$2a$12$placeholder_hash_for_HubSpotAustralia@2026', 'user', 1, NOW()),
('thomas', 'lopez', 'thomas.lopez14@gmail.com', 'User', 'HubSpot Australia', 'Australia', '$2a$12$placeholder_hash_for_HubSpotAustralia@2026', 'user', 1, NOW()),
('evelyn', 'clark', 'evelyn.clark31@yahoo.com', 'User', 'Infusionsoft Australia', 'Australia', '$2a$12$placeholder_hash_for_InfusionsoftAustralia@2026', 'user', 1, NOW()),
('lily', 'hernandez', 'lily.hernandez46@hotmail.com', 'User', 'Infusionsoft Australia', 'Australia', '$2a$12$placeholder_hash_for_InfusionsoftAustralia@2026', 'user', 1, NOW()),
('abigail', 'lopez', 'abigail.lopez21@outlook.com', 'User', 'Insightly Australia', 'Australia', '$2a$12$placeholder_hash_for_InsightlyAustralia@2026', 'user', 1, NOW()),
('ella', 'williams', 'ella.williams35@gmail.com', 'User', 'Insightly Australia', 'Australia', '$2a$12$placeholder_hash_for_InsightlyAustralia@2026', 'user', 1, NOW()),
('evie', 'brown', 'evie.brown28@yahoo.com', 'User', 'Insightly Australia', 'Australia', '$2a$12$placeholder_hash_for_InsightlyAustralia@2026', 'user', 1, NOW()),
('grace', 'brown', 'grace.brown73@yahoo.com', 'User', 'Insightly Australia', 'Australia', '$2a$12$placeholder_hash_for_InsightlyAustralia@2026', 'user', 1, NOW()),
('jack', 'rodriguez', 'jack.rodriguez75@hotmail.com', 'User', 'Insightly Australia', 'Australia', '$2a$12$placeholder_hash_for_InsightlyAustralia@2026', 'user', 1, NOW()),
('james', 'robinson', 'james.robinson23@gmail.com', 'User', 'Lattice Engines Australia', 'Australia', '$2a$12$placeholder_hash_for_LatticeEnginesAustralia@2026', 'user', 1, NOW()),
('noah', 'robinson', 'noah.robinson41@gmail.com', 'User', 'Lattice Engines Australia', 'Australia', '$2a$12$placeholder_hash_for_LatticeEnginesAustralia@2026', 'user', 1, NOW()),
('olivia', 'davis', 'olivia.davis26@gmail.com', 'User', 'Lattice Engines Australia', 'Australia', '$2a$12$placeholder_hash_for_LatticeEnginesAustralia@2026', 'user', 1, NOW()),
('thomas', 'robinson', 'thomas.robinson66@company.com', 'User', 'Lattice Engines Australia', 'Australia', '$2a$12$placeholder_hash_for_LatticeEnginesAustralia@2026', 'user', 1, NOW()),
('harper', 'garcia', 'harper.garcia45@hotmail.com', 'User', 'LeadFeeder Australia', 'Australia', '$2a$12$placeholder_hash_for_LeadFeederAustralia@2026', 'user', 1, NOW()),
('harper', 'white', 'harper.white62@gmail.com', 'User', 'LeadFeeder Australia', 'Australia', '$2a$12$placeholder_hash_for_LeadFeederAustralia@2026', 'user', 1, NOW()),
('mason', 'lee', 'mason.lee6@company.com', 'User', 'LeadFeeder Australia', 'Australia', '$2a$12$placeholder_hash_for_LeadFeederAustralia@2026', 'user', 1, NOW()),
('olivia', 'hernandez', 'olivia.hernandez49@yahoo.com', 'User', 'LeadFeeder Australia', 'Australia', '$2a$12$placeholder_hash_for_LeadFeederAustralia@2026', 'user', 1, NOW()),
('hannah', 'lopez', 'hannah.lopez57@company.com', 'User', 'LeadSquared Australia', 'Australia', '$2a$12$placeholder_hash_for_LeadSquaredAustralia@2026', 'user', 1, NOW()),
('lily', 'williams', 'lily.williams67@company.com', 'User', 'LeadSquared Australia', 'Australia', '$2a$12$placeholder_hash_for_LeadSquaredAustralia@2026', 'user', 1, NOW()),
('henry', 'jones', 'henry.jones71@outlook.com', 'User', 'Marketo Australia', 'Australia', '$2a$12$placeholder_hash_for_MarketoAustralia@2026', 'user', 1, NOW()),
('zoe', 'williams', 'zoe.williams18@company.com', 'User', 'Marketo Australia', 'Australia', '$2a$12$placeholder_hash_for_MarketoAustralia@2026', 'user', 1, NOW()),
('chloe', 'garcia', 'chloe.garcia33@yahoo.com', 'User', 'Oracle Marketing Cloud Australia', 'Australia', '$2a$12$placeholder_hash_for_OracleMarketingCloudAustralia@2026', 'user', 1, NOW()),
('thomas', 'johnson', 'thomas.johnson55@company.com', 'User', 'Oracle Marketing Cloud Australia', 'Australia', '$2a$12$placeholder_hash_for_OracleMarketingCloudAustralia@2026', 'user', 1, NOW()),
('zoe', 'jackson', 'zoe.jackson53@company.com', 'User', 'Oracle Marketing Cloud Australia', 'Australia', '$2a$12$placeholder_hash_for_OracleMarketingCloudAustralia@2026', 'user', 1, NOW()),
('chloe', 'wilson', 'chloe.wilson5@gmail.com', 'User', 'Outreach Australia', 'Australia', '$2a$12$placeholder_hash_for_OutreachAustralia@2026', 'user', 1, NOW()),
('harper', 'johnson', 'harper.johnson7@yahoo.com', 'User', 'Outreach Australia', 'Australia', '$2a$12$placeholder_hash_for_OutreachAustralia@2026', 'user', 1, NOW()),
('amelia', 'thompson', 'amelia.thompson47@company.com', 'User', 'Pardot Australia', 'Australia', '$2a$12$placeholder_hash_for_PardotAustralia@2026', 'user', 1, NOW()),
('ella', 'white', 'ella.white9@company.com', 'User', 'Pardot Australia', 'Australia', '$2a$12$placeholder_hash_for_PardotAustralia@2026', 'user', 1, NOW()),
('isla', 'martin', 'isla.martin63@hotmail.com', 'User', 'Pardot Australia', 'Australia', '$2a$12$placeholder_hash_for_PardotAustralia@2026', 'user', 1, NOW()),
('noah', 'rodriguez', 'noah.rodriguez74@company.com', 'User', 'Pardot Australia', 'Australia', '$2a$12$placeholder_hash_for_PardotAustralia@2026', 'user', 1, NOW()),
('olivia', 'garcia', 'olivia.garcia19@gmail.com', 'User', 'Pardot Australia', 'Australia', '$2a$12$placeholder_hash_for_PardotAustralia@2026', 'user', 1, NOW()),
('grace', 'thompson', 'grace.thompson54@yahoo.com', 'User', 'Salesforce Australia', 'Australia', '$2a$12$placeholder_hash_for_SalesforceAustralia@2026', 'user', 1, NOW()),
('mia', 'davis', 'mia.davis20@outlook.com', 'User', 'Salesforce Australia', 'Australia', '$2a$12$placeholder_hash_for_SalesforceAustralia@2026', 'user', 1, NOW()),
('abigail', 'taylor', 'abigail.taylor8@outlook.com', 'User', 'Salesfusion Australia', 'Australia', '$2a$12$placeholder_hash_for_SalesfusionAustralia@2026', 'user', 1, NOW()),
('mia', 'miller', 'mia.miller15@outlook.com', 'User', 'Salesfusion Australia', 'Australia', '$2a$12$placeholder_hash_for_SalesfusionAustralia@2026', 'user', 1, NOW()),
('evelyn', 'johnson', 'evelyn.johnson44@gmail.com', 'User', 'SharpSpring Australia', 'Australia', '$2a$12$placeholder_hash_for_SharpSpringAustralia@2026', 'user', 1, NOW()),
('grace', 'thomas', 'grace.thomas12@company.com', 'User', 'SharpSpring Australia', 'Australia', '$2a$12$placeholder_hash_for_SharpSpringAustralia@2026', 'user', 1, NOW()),
('evelyn', 'williams', 'evelyn.williams32@company.com', 'User', 'Woodpecker Australia', 'Australia', '$2a$12$placeholder_hash_for_WoodpeckerAustralia@2026', 'user', 1, NOW()),
('henry', 'thomas', 'henry.thomas10@yahoo.com', 'User', 'Woodpecker Australia', 'Australia', '$2a$12$placeholder_hash_for_WoodpeckerAustralia@2026', 'user', 1, NOW()),
('jack', 'brown', 'jack.brown37@gmail.com', 'User', 'Woodpecker Australia', 'Australia', '$2a$12$placeholder_hash_for_WoodpeckerAustralia@2026', 'user', 1, NOW()),
('mason', 'martinez', 'mason.martinez70@gmail.com', 'User', 'Woodpecker Australia', 'Australia', '$2a$12$placeholder_hash_for_WoodpeckerAustralia@2026', 'user', 1, NOW()),
('chloe', 'gonzalez', 'chloe.gonzalez29@hotmail.com', 'User', 'ZoomInfo Australia', 'Australia', '$2a$12$placeholder_hash_for_ZoomInfoAustralia@2026', 'user', 1, NOW()),
('elizabeth', 'thompson', 'elizabeth.thompson16@gmail.com', 'User', '6sense Canada', 'Canada', '$2a$12$placeholder_hash_for_6senseCanada@2026', 'user', 1, NOW()),
('victoria', 'williams', 'victoria.williams17@company.com', 'User', '6sense Canada', 'Canada', '$2a$12$placeholder_hash_for_6senseCanada@2026', 'user', 1, NOW()),
('mia', 'gonzalez', 'mia.gonzalez43@company.com', 'User', 'Act-On Canada', 'Canada', '$2a$12$placeholder_hash_for_Act-OnCanada@2026', 'user', 1, NOW()),
('olivia', 'johnson', 'olivia.johnson12@gmail.com', 'User', 'Act-On Canada', 'Canada', '$2a$12$placeholder_hash_for_Act-OnCanada@2026', 'user', 1, NOW()),
('amelia', 'davis', 'amelia.davis44@company.com', 'User', 'Autopilot Canada', 'Canada', '$2a$12$placeholder_hash_for_AutopilotCanada@2026', 'user', 1, NOW()),
('mia', 'martin', 'mia.martin1@yahoo.com', 'User', 'Autopilot Canada', 'Canada', '$2a$12$placeholder_hash_for_AutopilotCanada@2026', 'user', 1, NOW()),
('stella', 'miller', 'stella.miller45@outlook.com', 'User', 'Autopilot Canada', 'Canada', '$2a$12$placeholder_hash_for_AutopilotCanada@2026', 'user', 1, NOW()),
('mason', 'rodriguez', 'mason.rodriguez59@outlook.com', 'User', 'Bombora Canada', 'Canada', '$2a$12$placeholder_hash_for_BomboraCanada@2026', 'user', 1, NOW()),
('benjamin', 'jackson', 'benjamin.jackson29@yahoo.com', 'User', 'Clearbit Canada', 'Canada', '$2a$12$placeholder_hash_for_ClearbitCanada@2026', 'user', 1, NOW()),
('jackson', 'rodriguez', 'jackson.rodriguez60@outlook.com', 'User', 'Clearbit Canada', 'Canada', '$2a$12$placeholder_hash_for_ClearbitCanada@2026', 'user', 1, NOW()),
('avery', 'anderson', 'avery.anderson35@yahoo.com', 'User', 'Demandbase Canada', 'Canada', '$2a$12$placeholder_hash_for_DemandbaseCanada@2026', 'user', 1, NOW()),
('olivia', 'miller', 'olivia.miller10@gmail.com', 'User', 'Demandbase Canada', 'Canada', '$2a$12$placeholder_hash_for_DemandbaseCanada@2026', 'user', 1, NOW()),
('logan', 'jones', 'logan.jones2@hotmail.com', 'User', 'Drip Canada', 'Canada', '$2a$12$placeholder_hash_for_DripCanada@2026', 'user', 1, NOW()),
('chloe', 'davis', 'chloe.davis56@gmail.com', 'User', 'Dun & Bradstreet Canada', 'Canada', '$2a$12$placeholder_hash_for_Dun&BradstreetCanada@2026', 'user', 1, NOW()),
('ethan', 'martinez', 'ethan.martinez24@yahoo.com', 'User', 'Dun & Bradstreet Canada', 'Canada', '$2a$12$placeholder_hash_for_Dun&BradstreetCanada@2026', 'user', 1, NOW()),
('emily', 'johnson', 'emily.johnson22@gmail.com', 'User', 'Eloqua Canada', 'Canada', '$2a$12$placeholder_hash_for_EloquaCanada@2026', 'user', 1, NOW()),
('evelyn', 'miller', 'evelyn.miller58@gmail.com', 'User', 'Eloqua Canada', 'Canada', '$2a$12$placeholder_hash_for_EloquaCanada@2026', 'user', 1, NOW()),
('levi', 'jackson', 'levi.jackson28@gmail.com', 'User', 'Eloqua Canada', 'Canada', '$2a$12$placeholder_hash_for_EloquaCanada@2026', 'user', 1, NOW()),
('logan', 'smith', 'logan.smith20@gmail.com', 'User', 'Eloqua Canada', 'Canada', '$2a$12$placeholder_hash_for_EloquaCanada@2026', 'user', 1, NOW()),
('chloe', 'johnson', 'chloe.johnson14@outlook.com', 'User', 'Freshworks Canada', 'Canada', '$2a$12$placeholder_hash_for_FreshworksCanada@2026', 'user', 1, NOW()),
('evelyn', 'brown', 'evelyn.brown33@company.com', 'User', 'Freshworks Canada', 'Canada', '$2a$12$placeholder_hash_for_FreshworksCanada@2026', 'user', 1, NOW()),
('stella', 'sanchez', 'stella.sanchez7@company.com', 'User', 'Freshworks Canada', 'Canada', '$2a$12$placeholder_hash_for_FreshworksCanada@2026', 'user', 1, NOW()),
('nora', 'garcia', 'nora.garcia4@outlook.com', 'User', 'HubSpot Canada', 'Canada', '$2a$12$placeholder_hash_for_HubSpotCanada@2026', 'user', 1, NOW()),
('scarlett', 'smith', 'scarlett.smith61@yahoo.com', 'User', 'HubSpot Canada', 'Canada', '$2a$12$placeholder_hash_for_HubSpotCanada@2026', 'user', 1, NOW()),
('sofia', 'anderson', 'sofia.anderson48@company.com', 'User', 'HubSpot Canada', 'Canada', '$2a$12$placeholder_hash_for_HubSpotCanada@2026', 'user', 1, NOW()),
('harper', 'taylor', 'harper.taylor13@hotmail.com', 'User', 'Infusionsoft Canada', 'Canada', '$2a$12$placeholder_hash_for_InfusionsoftCanada@2026', 'user', 1, NOW()),
('hazel', 'lopez', 'hazel.lopez3@yahoo.com', 'User', 'Infusionsoft Canada', 'Canada', '$2a$12$placeholder_hash_for_InfusionsoftCanada@2026', 'user', 1, NOW()),
('mason', 'thomas', 'mason.thomas41@outlook.com', 'User', 'Infusionsoft Canada', 'Canada', '$2a$12$placeholder_hash_for_InfusionsoftCanada@2026', 'user', 1, NOW()),
('grace', 'thomas', 'grace.thomas8@gmail.com', 'User', 'Insightly Canada', 'Canada', '$2a$12$placeholder_hash_for_InsightlyCanada@2026', 'user', 1, NOW()),
('mason', 'thomas', 'mason.thomas31@company.com', 'User', 'Insightly Canada', 'Canada', '$2a$12$placeholder_hash_for_InsightlyCanada@2026', 'user', 1, NOW()),
('amelia', 'brown', 'amelia.brown26@outlook.com', 'User', 'Lattice Engines Canada', 'Canada', '$2a$12$placeholder_hash_for_LatticeEnginesCanada@2026', 'user', 1, NOW()),
('evelyn', 'wilson', 'evelyn.wilson5@hotmail.com', 'User', 'Lattice Engines Canada', 'Canada', '$2a$12$placeholder_hash_for_LatticeEnginesCanada@2026', 'user', 1, NOW()),
('nora', 'ramirez', 'nora.ramirez54@company.com', 'User', 'Lattice Engines Canada', 'Canada', '$2a$12$placeholder_hash_for_LatticeEnginesCanada@2026', 'user', 1, NOW()),
('elizabeth', 'johnson', 'elizabeth.johnson40@outlook.com', 'User', 'LeadFeeder Canada', 'Canada', '$2a$12$placeholder_hash_for_LeadFeederCanada@2026', 'user', 1, NOW()),
('grace', 'thomas', 'grace.thomas6@company.com', 'User', 'LeadFeeder Canada', 'Canada', '$2a$12$placeholder_hash_for_LeadFeederCanada@2026', 'user', 1, NOW()),
('levi', 'johnson', 'levi.johnson30@gmail.com', 'User', 'LeadSquared Canada', 'Canada', '$2a$12$placeholder_hash_for_LeadSquaredCanada@2026', 'user', 1, NOW()),
('amelia', 'taylor', 'amelia.taylor52@company.com', 'User', 'Marketo Canada', 'Canada', '$2a$12$placeholder_hash_for_MarketoCanada@2026', 'user', 1, NOW()),
('ella', 'harris', 'ella.harris19@hotmail.com', 'User', 'Marketo Canada', 'Canada', '$2a$12$placeholder_hash_for_MarketoCanada@2026', 'user', 1, NOW()),
('ella', 'jones', 'ella.jones57@company.com', 'User', 'Marketo Canada', 'Canada', '$2a$12$placeholder_hash_for_MarketoCanada@2026', 'user', 1, NOW()),
('ethan', 'miller', 'ethan.miller25@hotmail.com', 'User', 'Marketo Canada', 'Canada', '$2a$12$placeholder_hash_for_MarketoCanada@2026', 'user', 1, NOW()),
('evelyn', 'anderson', 'evelyn.anderson27@yahoo.com', 'User', 'Marketo Canada', 'Canada', '$2a$12$placeholder_hash_for_MarketoCanada@2026', 'user', 1, NOW()),
('ava', 'davis', 'ava.davis18@outlook.com', 'User', 'Oracle Marketing Cloud Canada', 'Canada', '$2a$12$placeholder_hash_for_OracleMarketingCloudCanada@2026', 'user', 1, NOW()),
('elizabeth', 'wilson', 'elizabeth.wilson53@yahoo.com', 'User', 'Oracle Marketing Cloud Canada', 'Canada', '$2a$12$placeholder_hash_for_OracleMarketingCloudCanada@2026', 'user', 1, NOW()),
('jackson', 'smith', 'jackson.smith15@gmail.com', 'User', 'Oracle Marketing Cloud Canada', 'Canada', '$2a$12$placeholder_hash_for_OracleMarketingCloudCanada@2026', 'user', 1, NOW()),
('ella', 'harris', 'ella.harris50@hotmail.com', 'User', 'Outreach Canada', 'Canada', '$2a$12$placeholder_hash_for_OutreachCanada@2026', 'user', 1, NOW()),
('evelyn', 'lewis', 'evelyn.lewis55@gmail.com', 'User', 'Outreach Canada', 'Canada', '$2a$12$placeholder_hash_for_OutreachCanada@2026', 'user', 1, NOW()),
('madison', 'garcia', 'madison.garcia42@company.com', 'User', 'Pardot Canada', 'Canada', '$2a$12$placeholder_hash_for_PardotCanada@2026', 'user', 1, NOW()),
('isabella', 'garcia', 'isabella.garcia9@hotmail.com', 'User', 'Salesforce Canada', 'Canada', '$2a$12$placeholder_hash_for_SalesforceCanada@2026', 'user', 1, NOW()),
('zoey', 'garcia', 'zoey.garcia39@company.com', 'User', 'Salesforce Canada', 'Canada', '$2a$12$placeholder_hash_for_SalesforceCanada@2026', 'user', 1, NOW()),
('abigail', 'perez', 'abigail.perez51@outlook.com', 'User', 'Salesfusion Canada', 'Canada', '$2a$12$placeholder_hash_for_SalesfusionCanada@2026', 'user', 1, NOW()),
('amelia', 'davis', 'amelia.davis38@gmail.com', 'User', 'Salesfusion Canada', 'Canada', '$2a$12$placeholder_hash_for_SalesfusionCanada@2026', 'user', 1, NOW()),
('madison', 'sanchez', 'madison.sanchez36@outlook.com', 'User', 'SharpSpring Canada', 'Canada', '$2a$12$placeholder_hash_for_SharpSpringCanada@2026', 'user', 1, NOW()),
('mia', 'smith', 'mia.smith47@outlook.com', 'User', 'SharpSpring Canada', 'Canada', '$2a$12$placeholder_hash_for_SharpSpringCanada@2026', 'user', 1, NOW()),
('abigail', 'hernandez', 'abigail.hernandez21@hotmail.com', 'User', 'Woodpecker Canada', 'Canada', '$2a$12$placeholder_hash_for_WoodpeckerCanada@2026', 'user', 1, NOW()),
('lily', 'martin', 'lily.martin34@gmail.com', 'User', 'Woodpecker Canada', 'Canada', '$2a$12$placeholder_hash_for_WoodpeckerCanada@2026', 'user', 1, NOW()),
('ava', 'anderson', 'ava.anderson23@hotmail.com', 'User', 'Zoho Canada', 'Canada', '$2a$12$placeholder_hash_for_ZohoCanada@2026', 'user', 1, NOW()),
('lucas', 'rodriguez', 'lucas.rodriguez49@company.com', 'User', 'Zoho Canada', 'Canada', '$2a$12$placeholder_hash_for_ZohoCanada@2026', 'user', 1, NOW()),
('mia', 'smith', 'mia.smith37@company.com', 'User', 'Zoho Canada', 'Canada', '$2a$12$placeholder_hash_for_ZohoCanada@2026', 'user', 1, NOW()),
('oliver', 'johnson', 'oliver.johnson11@yahoo.com', 'User', 'Zoho Canada', 'Canada', '$2a$12$placeholder_hash_for_ZohoCanada@2026', 'user', 1, NOW()),
('luna', 'hernandez', 'luna.hernandez46@hotmail.com', 'User', 'ZoomInfo Canada', 'Canada', '$2a$12$placeholder_hash_for_ZoomInfoCanada@2026', 'user', 1, NOW()),
('stella', 'rodriguez', 'stella.rodriguez32@yahoo.com', 'User', 'ZoomInfo Canada', 'Canada', '$2a$12$placeholder_hash_for_ZoomInfoCanada@2026', 'user', 1, NOW()),
('jade', 'boyer', 'jade.boyer22@hotmail.com', 'User', '6sense France', 'France', '$2a$12$placeholder_hash_for_6senseFrance@2026', 'user', 1, NOW()),
('lucas', 'gillet', 'lucas.gillet44@outlook.com', 'User', 'Act-On France', 'France', '$2a$12$placeholder_hash_for_Act-OnFrance@2026', 'user', 1, NOW()),
('jade', 'michel', 'jade.michel1@hotmail.com', 'User', 'Autopilot France', 'France', '$2a$12$placeholder_hash_for_AutopilotFrance@2026', 'user', 1, NOW()),
('camille', 'leroy', 'camille.leroy42@yahoo.com', 'User', 'Bombora France', 'France', '$2a$12$placeholder_hash_for_BomboraFrance@2026', 'user', 1, NOW()),
('adam', 'david', 'adam.david26@yahoo.com', 'User', 'Clearbit France', 'France', '$2a$12$placeholder_hash_for_ClearbitFrance@2026', 'user', 1, NOW()),
('alice', 'vincent', 'alice.vincent43@yahoo.com', 'User', 'Clearbit France', 'France', '$2a$12$placeholder_hash_for_ClearbitFrance@2026', 'user', 1, NOW()),
('emma', 'bertrand', 'emma.bertrand34@hotmail.com', 'User', 'Clearbit France', 'France', '$2a$12$placeholder_hash_for_ClearbitFrance@2026', 'user', 1, NOW()),
('enzo', 'mercier', 'enzo.mercier54@company.com', 'User', 'Clearbit France', 'France', '$2a$12$placeholder_hash_for_ClearbitFrance@2026', 'user', 1, NOW()),
('hugo', 'durand', 'hugo.durand7@company.com', 'User', 'Clearbit France', 'France', '$2a$12$placeholder_hash_for_ClearbitFrance@2026', 'user', 1, NOW()),
('eva', 'lefebvre', 'eva.lefebvre47@yahoo.com', 'User', 'Demandbase France', 'France', '$2a$12$placeholder_hash_for_DemandbaseFrance@2026', 'user', 1, NOW()),
('louis', 'bertrand', 'louis.bertrand36@hotmail.com', 'User', 'Demandbase France', 'France', '$2a$12$placeholder_hash_for_DemandbaseFrance@2026', 'user', 1, NOW()),
('zoé', 'mercier', 'zoé.mercier55@company.com', 'User', 'Demandbase France', 'France', '$2a$12$placeholder_hash_for_DemandbaseFrance@2026', 'user', 1, NOW()),
('marie', 'bernard', 'marie.bernard30@company.com', 'User', 'Drip France', 'France', '$2a$12$placeholder_hash_for_DripFrance@2026', 'user', 1, NOW()),
('adèle', 'vincent', 'adèle.vincent33@gmail.com', 'User', 'Dun & Bradstreet France', 'France', '$2a$12$placeholder_hash_for_Dun&BradstreetFrance@2026', 'user', 1, NOW()),
('jasmine', 'bernard', 'jasmine.bernard49@yahoo.com', 'User', 'Dun & Bradstreet France', 'France', '$2a$12$placeholder_hash_for_Dun&BradstreetFrance@2026', 'user', 1, NOW()),
('léa', 'david', 'léa.david53@hotmail.com', 'User', 'Dun & Bradstreet France', 'France', '$2a$12$placeholder_hash_for_Dun&BradstreetFrance@2026', 'user', 1, NOW()),
('marie', 'garcia', 'marie.garcia18@yahoo.com', 'User', 'Eloqua France', 'France', '$2a$12$placeholder_hash_for_EloquaFrance@2026', 'user', 1, NOW()),
('romane', 'fournier', 'romane.fournier48@company.com', 'User', 'Eloqua France', 'France', '$2a$12$placeholder_hash_for_EloquaFrance@2026', 'user', 1, NOW()),
('raphaël', 'michel', 'raphaël.michel23@hotmail.com', 'User', 'Freshworks France', 'France', '$2a$12$placeholder_hash_for_FreshworksFrance@2026', 'user', 1, NOW()),
('léa', 'thomas', 'léa.thomas11@company.com', 'User', 'HubSpot France', 'France', '$2a$12$placeholder_hash_for_HubSpotFrance@2026', 'user', 1, NOW()),
('inès', 'michel', 'inès.michel35@yahoo.com', 'User', 'Infusionsoft France', 'France', '$2a$12$placeholder_hash_for_InfusionsoftFrance@2026', 'user', 1, NOW()),
('lucas', 'vincent', 'lucas.vincent31@yahoo.com', 'User', 'Insightly France', 'France', '$2a$12$placeholder_hash_for_InsightlyFrance@2026', 'user', 1, NOW()),
('chloé', 'mercier', 'chloé.mercier58@company.com', 'User', 'Lattice Engines France', 'France', '$2a$12$placeholder_hash_for_LatticeEnginesFrance@2026', 'user', 1, NOW()),
('enzo', 'richard', 'enzo.richard52@outlook.com', 'User', 'Lattice Engines France', 'France', '$2a$12$placeholder_hash_for_LatticeEnginesFrance@2026', 'user', 1, NOW()),
('hugo', 'leclerc', 'hugo.leclerc19@company.com', 'User', 'Lattice Engines France', 'France', '$2a$12$placeholder_hash_for_LatticeEnginesFrance@2026', 'user', 1, NOW()),
('manon', 'leroy', 'manon.leroy13@hotmail.com', 'User', 'Lattice Engines France', 'France', '$2a$12$placeholder_hash_for_LatticeEnginesFrance@2026', 'user', 1, NOW()),
('sarah', 'garcia', 'sarah.garcia12@company.com', 'User', 'Lattice Engines France', 'France', '$2a$12$placeholder_hash_for_LatticeEnginesFrance@2026', 'user', 1, NOW()),
('adèle', 'gillet', 'adèle.gillet6@company.com', 'User', 'LeadFeeder France', 'France', '$2a$12$placeholder_hash_for_LeadFeederFrance@2026', 'user', 1, NOW()),
('léo', 'richard', 'léo.richard40@hotmail.com', 'User', 'LeadFeeder France', 'France', '$2a$12$placeholder_hash_for_LeadFeederFrance@2026', 'user', 1, NOW()),
('lina', 'lefebvre', 'lina.lefebvre17@outlook.com', 'User', 'LeadFeeder France', 'France', '$2a$12$placeholder_hash_for_LeadFeederFrance@2026', 'user', 1, NOW()),
('raphaël', 'leclerc', 'raphaël.leclerc3@company.com', 'User', 'LeadFeeder France', 'France', '$2a$12$placeholder_hash_for_LeadFeederFrance@2026', 'user', 1, NOW()),
('chloé', 'morel', 'chloé.morel20@yahoo.com', 'User', 'LeadSquared France', 'France', '$2a$12$placeholder_hash_for_LeadSquaredFrance@2026', 'user', 1, NOW()),
('jules', 'simon', 'jules.simon46@yahoo.com', 'User', 'LeadSquared France', 'France', '$2a$12$placeholder_hash_for_LeadSquaredFrance@2026', 'user', 1, NOW()),
('clara', 'mercier', 'clara.mercier39@company.com', 'User', 'Marketo France', 'France', '$2a$12$placeholder_hash_for_MarketoFrance@2026', 'user', 1, NOW()),
('chloé', 'richard', 'chloé.richard25@hotmail.com', 'User', 'Oracle Marketing Cloud France', 'France', '$2a$12$placeholder_hash_for_OracleMarketingCloudFrance@2026', 'user', 1, NOW()),
('emma', 'blanc', 'emma.blanc28@outlook.com', 'User', 'Oracle Marketing Cloud France', 'France', '$2a$12$placeholder_hash_for_OracleMarketingCloudFrance@2026', 'user', 1, NOW()),
('jade', 'martinez', 'jade.martinez37@company.com', 'User', 'Oracle Marketing Cloud France', 'France', '$2a$12$placeholder_hash_for_OracleMarketingCloudFrance@2026', 'user', 1, NOW()),
('raphaël', 'martinez', 'raphaël.martinez56@gmail.com', 'User', 'Oracle Marketing Cloud France', 'France', '$2a$12$placeholder_hash_for_OracleMarketingCloudFrance@2026', 'user', 1, NOW()),
('eva', 'thomas', 'eva.thomas45@outlook.com', 'User', 'Outreach France', 'France', '$2a$12$placeholder_hash_for_OutreachFrance@2026', 'user', 1, NOW()),
('manon', 'robert', 'manon.robert15@yahoo.com', 'User', 'Outreach France', 'France', '$2a$12$placeholder_hash_for_OutreachFrance@2026', 'user', 1, NOW()),
('marie', 'bernard', 'marie.bernard51@gmail.com', 'User', 'Pardot France', 'France', '$2a$12$placeholder_hash_for_PardotFrance@2026', 'user', 1, NOW()),
('raphaël', 'leclerc', 'raphaël.leclerc32@outlook.com', 'User', 'Salesforce France', 'France', '$2a$12$placeholder_hash_for_SalesforceFrance@2026', 'user', 1, NOW()),
('emma', 'vincent', 'emma.vincent24@gmail.com', 'User', 'Salesfusion France', 'France', '$2a$12$placeholder_hash_for_SalesfusionFrance@2026', 'user', 1, NOW()),
('eva', 'dubois', 'eva.dubois57@gmail.com', 'User', 'Salesfusion France', 'France', '$2a$12$placeholder_hash_for_SalesfusionFrance@2026', 'user', 1, NOW()),
('jasmine', 'dubois', 'jasmine.dubois38@company.com', 'User', 'SharpSpring France', 'France', '$2a$12$placeholder_hash_for_SharpSpringFrance@2026', 'user', 1, NOW()),
('jeanne', 'blanc', 'jeanne.blanc27@yahoo.com', 'User', 'SharpSpring France', 'France', '$2a$12$placeholder_hash_for_SharpSpringFrance@2026', 'user', 1, NOW()),
('adèle', 'michel', 'adèle.michel21@yahoo.com', 'User', 'Woodpecker France', 'France', '$2a$12$placeholder_hash_for_WoodpeckerFrance@2026', 'user', 1, NOW()),
('enzo', 'dubois', 'enzo.dubois8@yahoo.com', 'User', 'Woodpecker France', 'France', '$2a$12$placeholder_hash_for_WoodpeckerFrance@2026', 'user', 1, NOW()),
('jade', 'mercier', 'jade.mercier9@company.com', 'User', 'Woodpecker France', 'France', '$2a$12$placeholder_hash_for_WoodpeckerFrance@2026', 'user', 1, NOW()),
('raphaël', 'garcia', 'raphaël.garcia10@outlook.com', 'User', 'Woodpecker France', 'France', '$2a$12$placeholder_hash_for_WoodpeckerFrance@2026', 'user', 1, NOW()),
('julie', 'robert', 'julie.robert16@gmail.com', 'User', 'Zoho France', 'France', '$2a$12$placeholder_hash_for_ZohoFrance@2026', 'user', 1, NOW()),
('agathe', 'morel', 'agathe.morel4@gmail.com', 'User', 'ZoomInfo France', 'France', '$2a$12$placeholder_hash_for_ZoomInfoFrance@2026', 'user', 1, NOW()),
('camille', 'guérin', 'camille.guérin5@outlook.com', 'User', 'ZoomInfo France', 'France', '$2a$12$placeholder_hash_for_ZoomInfoFrance@2026', 'user', 1, NOW()),
('enzo', 'blanc', 'enzo.blanc14@gmail.com', 'User', 'ZoomInfo France', 'France', '$2a$12$placeholder_hash_for_ZoomInfoFrance@2026', 'user', 1, NOW()),
('jeanne', 'vincent', 'jeanne.vincent29@outlook.com', 'User', 'ZoomInfo France', 'France', '$2a$12$placeholder_hash_for_ZoomInfoFrance@2026', 'user', 1, NOW()),
('lucas', 'simon', 'lucas.simon50@gmail.com', 'User', 'ZoomInfo France', 'France', '$2a$12$placeholder_hash_for_ZoomInfoFrance@2026', 'user', 1, NOW()),
('marie', 'bernard', 'marie.bernard2@gmail.com', 'User', 'ZoomInfo France', 'France', '$2a$12$placeholder_hash_for_ZoomInfoFrance@2026', 'user', 1, NOW()),
('pauline', 'thomas', 'pauline.thomas41@yahoo.com', 'User', 'ZoomInfo France', 'France', '$2a$12$placeholder_hash_for_ZoomInfoFrance@2026', 'user', 1, NOW()),
('amelie', 'vogel', 'amelie.vogel37@yahoo.com', 'User', '6sense Germany', 'Germany', '$2a$12$placeholder_hash_for_6senseGermany@2026', 'user', 1, NOW()),
('aurelia', 'schulz', 'aurelia.schulz13@company.com', 'User', '6sense Germany', 'Germany', '$2a$12$placeholder_hash_for_6senseGermany@2026', 'user', 1, NOW()),
('paula', 'krüger', 'paula.krüger6@outlook.com', 'User', '6sense Germany', 'Germany', '$2a$12$placeholder_hash_for_6senseGermany@2026', 'user', 1, NOW()),
('aurelia', 'martin', 'aurelia.martin34@gmail.com', 'User', 'Act-On Germany', 'Germany', '$2a$12$placeholder_hash_for_Act-OnGermany@2026', 'user', 1, NOW()),
('anna', 'meyer', 'anna.meyer55@gmail.com', 'User', 'Adobe Marketo Germany', 'Germany', '$2a$12$placeholder_hash_for_AdobeMarketoGermany@2026', 'user', 1, NOW()),
('hannah', 'vogel', 'hannah.vogel4@hotmail.com', 'User', 'Adobe Marketo Germany', 'Germany', '$2a$12$placeholder_hash_for_AdobeMarketoGermany@2026', 'user', 1, NOW()),
('elias', 'weidmann', 'elias.weidmann30@hotmail.com', 'User', 'Autopilot Germany', 'Germany', '$2a$12$placeholder_hash_for_AutopilotGermany@2026', 'user', 1, NOW()),
('emma', 'krüger', 'emma.krüger44@company.com', 'User', 'Autopilot Germany', 'Germany', '$2a$12$placeholder_hash_for_AutopilotGermany@2026', 'user', 1, NOW()),
('mia', 'richter', 'mia.richter9@gmail.com', 'User', 'Autopilot Germany', 'Germany', '$2a$12$placeholder_hash_for_AutopilotGermany@2026', 'user', 1, NOW()),
('sofia', 'neumann', 'sofia.neumann27@hotmail.com', 'User', 'Autopilot Germany', 'Germany', '$2a$12$placeholder_hash_for_AutopilotGermany@2026', 'user', 1, NOW()),
('emilia', 'meyer', 'emilia.meyer62@yahoo.com', 'User', 'Bombora Germany', 'Germany', '$2a$12$placeholder_hash_for_BomboraGermany@2026', 'user', 1, NOW()),
('emma', 'krüger', 'emma.krüger5@outlook.com', 'User', 'Clearbit Germany', 'Germany', '$2a$12$placeholder_hash_for_ClearbitGermany@2026', 'user', 1, NOW()),
('ella', 'vogel', 'ella.vogel11@yahoo.com', 'User', 'Demandbase Germany', 'Germany', '$2a$12$placeholder_hash_for_DemandbaseGermany@2026', 'user', 1, NOW()),
('lara', 'schneider', 'lara.schneider63@gmail.com', 'User', 'Demandbase Germany', 'Germany', '$2a$12$placeholder_hash_for_DemandbaseGermany@2026', 'user', 1, NOW()),
('lara', 'weber', 'lara.weber14@outlook.com', 'User', 'Demandbase Germany', 'Germany', '$2a$12$placeholder_hash_for_DemandbaseGermany@2026', 'user', 1, NOW()),
('nora', 'klein', 'nora.klein48@company.com', 'User', 'Demandbase Germany', 'Germany', '$2a$12$placeholder_hash_for_DemandbaseGermany@2026', 'user', 1, NOW()),
('emilia', 'hoffmann', 'emilia.hoffmann64@yahoo.com', 'User', 'Drip Germany', 'Germany', '$2a$12$placeholder_hash_for_DripGermany@2026', 'user', 1, NOW()),
('laura', 'zimmermann', 'laura.zimmermann31@gmail.com', 'User', 'Drip Germany', 'Germany', '$2a$12$placeholder_hash_for_DripGermany@2026', 'user', 1, NOW()),
('ella', 'schröder', 'ella.schröder29@hotmail.com', 'User', 'Dun & Bradstreet Germany', 'Germany', '$2a$12$placeholder_hash_for_Dun&BradstreetGermany@2026', 'user', 1, NOW()),
('marie', 'lehmann', 'marie.lehmann12@yahoo.com', 'User', 'Dun & Bradstreet Germany', 'Germany', '$2a$12$placeholder_hash_for_Dun&BradstreetGermany@2026', 'user', 1, NOW()),
('ben', 'zimmermann', 'ben.zimmermann39@gmail.com', 'User', 'Eloqua Germany', 'Germany', '$2a$12$placeholder_hash_for_EloquaGermany@2026', 'user', 1, NOW()),
('clara', 'schneider', 'clara.schneider2@outlook.com', 'User', 'Eloqua Germany', 'Germany', '$2a$12$placeholder_hash_for_EloquaGermany@2026', 'user', 1, NOW()),
('elisa', 'jung', 'elisa.jung49@company.com', 'User', 'Eloqua Germany', 'Germany', '$2a$12$placeholder_hash_for_EloquaGermany@2026', 'user', 1, NOW()),
('emma', 'beck', 'emma.beck24@yahoo.com', 'User', 'Freshworks Germany', 'Germany', '$2a$12$placeholder_hash_for_FreshworksGermany@2026', 'user', 1, NOW()),
('leon', 'zimmermann', 'leon.zimmermann21@hotmail.com', 'User', 'Freshworks Germany', 'Germany', '$2a$12$placeholder_hash_for_FreshworksGermany@2026', 'user', 1, NOW()),
('lina', 'wolf', 'lina.wolf25@outlook.com', 'User', 'Freshworks Germany', 'Germany', '$2a$12$placeholder_hash_for_FreshworksGermany@2026', 'user', 1, NOW()),
('maya', 'weber', 'maya.weber59@outlook.com', 'User', 'Freshworks Germany', 'Germany', '$2a$12$placeholder_hash_for_FreshworksGermany@2026', 'user', 1, NOW()),
('mila', 'vogel', 'mila.vogel43@outlook.com', 'User', 'Freshworks Germany', 'Germany', '$2a$12$placeholder_hash_for_FreshworksGermany@2026', 'user', 1, NOW()),
('mina', 'weidmann', 'mina.weidmann19@yahoo.com', 'User', 'Freshworks Germany', 'Germany', '$2a$12$placeholder_hash_for_FreshworksGermany@2026', 'user', 1, NOW()),
('mina', 'lange', 'mina.lange58@company.com', 'User', 'Freshworks Germany', 'Germany', '$2a$12$placeholder_hash_for_FreshworksGermany@2026', 'user', 1, NOW()),
('romy', 'lehmann', 'romy.lehmann65@company.com', 'User', 'Freshworks Germany', 'Germany', '$2a$12$placeholder_hash_for_FreshworksGermany@2026', 'user', 1, NOW()),
('lara', 'meyer', 'lara.meyer60@hotmail.com', 'User', 'HubSpot Germany', 'Germany', '$2a$12$placeholder_hash_for_HubSpotGermany@2026', 'user', 1, NOW()),
('mia', 'martin', 'mia.martin3@company.com', 'User', 'HubSpot Germany', 'Germany', '$2a$12$placeholder_hash_for_HubSpotGermany@2026', 'user', 1, NOW()),
('mathilda', 'schulz', 'mathilda.schulz32@gmail.com', 'User', 'LeadFeeder Germany', 'Germany', '$2a$12$placeholder_hash_for_LeadFeederGermany@2026', 'user', 1, NOW()),
('lea', 'weidmann', 'lea.weidmann57@hotmail.com', 'User', 'LeadSquared Germany', 'Germany', '$2a$12$placeholder_hash_for_LeadSquaredGermany@2026', 'user', 1, NOW()),
('lukas', 'neumann', 'lukas.neumann35@gmail.com', 'User', 'LeadSquared Germany', 'Germany', '$2a$12$placeholder_hash_for_LeadSquaredGermany@2026', 'user', 1, NOW()),
('max', 'schmid', 'max.schmid23@company.com', 'User', 'LeadSquared Germany', 'Germany', '$2a$12$placeholder_hash_for_LeadSquaredGermany@2026', 'user', 1, NOW()),
('mia', 'schulz', 'mia.schulz46@hotmail.com', 'User', 'LeadSquared Germany', 'Germany', '$2a$12$placeholder_hash_for_LeadSquaredGermany@2026', 'user', 1, NOW()),
('mia', 'schulz', 'mia.schulz54@outlook.com', 'User', 'LeadSquared Germany', 'Germany', '$2a$12$placeholder_hash_for_LeadSquaredGermany@2026', 'user', 1, NOW()),
('lukas', 'braun', 'lukas.braun45@company.com', 'User', 'Marketo Germany', 'Germany', '$2a$12$placeholder_hash_for_MarketoGermany@2026', 'user', 1, NOW()),
('sofia', 'vogel', 'sofia.vogel51@yahoo.com', 'User', 'Marketo Germany', 'Germany', '$2a$12$placeholder_hash_for_MarketoGermany@2026', 'user', 1, NOW()),
('lena', 'zimmermann', 'lena.zimmermann16@hotmail.com', 'User', 'Oracle Marketing Cloud Germany', 'Germany', '$2a$12$placeholder_hash_for_OracleMarketingCloudGermany@2026', 'user', 1, NOW()),
('lina', 'lehmann', 'lina.lehmann38@hotmail.com', 'User', 'Oracle Marketing Cloud Germany', 'Germany', '$2a$12$placeholder_hash_for_OracleMarketingCloudGermany@2026', 'user', 1, NOW()),
('lotta', 'klein', 'lotta.klein26@company.com', 'User', 'Oracle Marketing Cloud Germany', 'Germany', '$2a$12$placeholder_hash_for_OracleMarketingCloudGermany@2026', 'user', 1, NOW()),
('finn', 'köhler', 'finn.köhler10@hotmail.com', 'User', 'Outreach Germany', 'Germany', '$2a$12$placeholder_hash_for_OutreachGermany@2026', 'user', 1, NOW()),
('laura', 'wolf', 'laura.wolf8@yahoo.com', 'User', 'Outreach Germany', 'Germany', '$2a$12$placeholder_hash_for_OutreachGermany@2026', 'user', 1, NOW()),
('leon', 'vogel', 'leon.vogel56@hotmail.com', 'User', 'Outreach Germany', 'Germany', '$2a$12$placeholder_hash_for_OutreachGermany@2026', 'user', 1, NOW()),
('lara', 'klein', 'lara.klein61@company.com', 'User', 'Pardot Germany', 'Germany', '$2a$12$placeholder_hash_for_PardotGermany@2026', 'user', 1, NOW()),
('felix', 'schulz', 'felix.schulz28@outlook.com', 'User', 'Salesforce Germany', 'Germany', '$2a$12$placeholder_hash_for_SalesforceGermany@2026', 'user', 1, NOW()),
('felix', 'schwarz', 'felix.schwarz33@hotmail.com', 'User', 'Salesforce Germany', 'Germany', '$2a$12$placeholder_hash_for_SalesforceGermany@2026', 'user', 1, NOW()),
('finn', 'braun', 'finn.braun17@company.com', 'User', 'Salesforce Germany', 'Germany', '$2a$12$placeholder_hash_for_SalesforceGermany@2026', 'user', 1, NOW()),
('lara', 'wolf', 'lara.wolf50@outlook.com', 'User', 'Salesforce Germany', 'Germany', '$2a$12$placeholder_hash_for_SalesforceGermany@2026', 'user', 1, NOW()),
('lea', 'zimmermann', 'lea.zimmermann41@gmail.com', 'User', 'Salesforce Germany', 'Germany', '$2a$12$placeholder_hash_for_SalesforceGermany@2026', 'user', 1, NOW()),
('lukas', 'vogel', 'lukas.vogel7@outlook.com', 'User', 'Salesforce Germany', 'Germany', '$2a$12$placeholder_hash_for_SalesforceGermany@2026', 'user', 1, NOW()),
('marie', 'weber', 'marie.weber20@company.com', 'User', 'Salesforce Germany', 'Germany', '$2a$12$placeholder_hash_for_SalesforceGermany@2026', 'user', 1, NOW()),
('noah', 'hoffmann', 'noah.hoffmann22@company.com', 'User', 'Salesforce Germany', 'Germany', '$2a$12$placeholder_hash_for_SalesforceGermany@2026', 'user', 1, NOW()),
('lotta', 'schröder', 'lotta.schröder18@yahoo.com', 'User', 'Salesfusion Germany', 'Germany', '$2a$12$placeholder_hash_for_SalesfusionGermany@2026', 'user', 1, NOW()),
('leon', 'koch', 'leon.koch42@outlook.com', 'User', 'SharpSpring Germany', 'Germany', '$2a$12$placeholder_hash_for_SharpSpringGermany@2026', 'user', 1, NOW()),
('ella', 'martin', 'ella.martin53@yahoo.com', 'User', 'Woodpecker Germany', 'Germany', '$2a$12$placeholder_hash_for_WoodpeckerGermany@2026', 'user', 1, NOW()),
('mina', 'richter', 'mina.richter15@gmail.com', 'User', 'Woodpecker Germany', 'Germany', '$2a$12$placeholder_hash_for_WoodpeckerGermany@2026', 'user', 1, NOW()),
('lukas', 'koch', 'lukas.koch47@outlook.com', 'User', 'Zoho Germany', 'Germany', '$2a$12$placeholder_hash_for_ZohoGermany@2026', 'user', 1, NOW()),
('mila', 'köhler', 'mila.köhler52@yahoo.com', 'User', 'Zoho Germany', 'Germany', '$2a$12$placeholder_hash_for_ZohoGermany@2026', 'user', 1, NOW()),
('noah', 'lange', 'noah.lange40@gmail.com', 'User', 'Zoho Germany', 'Germany', '$2a$12$placeholder_hash_for_ZohoGermany@2026', 'user', 1, NOW()),
('paul', 'funk', 'paul.funk1@gmail.com', 'User', 'Zoho Germany', 'Germany', '$2a$12$placeholder_hash_for_ZohoGermany@2026', 'user', 1, NOW()),
('marie', 'jung', 'marie.jung36@outlook.com', 'User', 'ZoomInfo Germany', 'Germany', '$2a$12$placeholder_hash_for_ZoomInfoGermany@2026', 'user', 1, NOW()),
('advik', 'singh', 'advik.singh39@gmail.com', 'User', '6sense', 'India', '$2a$12$placeholder_hash_for_6sense@2026', 'user', 1, NOW()),
('anita', 'tiwari', 'anita.tiwari27@hotmail.com', 'User', 'Act-On', 'India', '$2a$12$placeholder_hash_for_Act-On@2026', 'user', 1, NOW()),
('neha', 'jain', 'neha.jain3@gmail.com', 'User', 'Act-On', 'India', '$2a$12$placeholder_hash_for_Act-On@2026', 'user', 1, NOW()),
('diya', 'patel', 'diya.patel1@outlook.com', 'User', 'Adobe Marketo', 'India', '$2a$12$placeholder_hash_for_AdobeMarketo@2026', 'user', 1, NOW()),
('priya', 'yadav', 'priya.yadav30@company.com', 'User', 'Bombora', 'India', '$2a$12$placeholder_hash_for_Bombora@2026', 'user', 1, NOW()),
('aditi', 'kumar', 'aditi.kumar10@gmail.com', 'User', 'ClickDimensions', 'India', '$2a$12$placeholder_hash_for_ClickDimensions@2026', 'user', 1, NOW()),
('kavya', 'saxena', 'kavya.saxena12@outlook.com', 'User', 'Demandbase', 'India', '$2a$12$placeholder_hash_for_Demandbase@2026', 'user', 1, NOW()),
('kiaan', 'nair', 'kiaan.nair6@company.com', 'User', 'Demandbase', 'India', '$2a$12$placeholder_hash_for_Demandbase@2026', 'user', 1, NOW()),
('aditya', 'patel', 'aditya.patel34@gmail.com', 'User', 'Drip', 'India', '$2a$12$placeholder_hash_for_Drip@2026', 'user', 1, NOW()),
('suresh', 'bhatia', 'suresh.bhatia35@outlook.com', 'User', 'Drip', 'India', '$2a$12$placeholder_hash_for_Drip@2026', 'user', 1, NOW()),
('veer', 'shah', 'veer.shah13@gmail.com', 'User', 'Dun & Bradstreet', 'India', '$2a$12$placeholder_hash_for_Dun&Bradstreet@2026', 'user', 1, NOW()),
('kavya', 'dubey', 'kavya.dubey28@yahoo.com', 'User', 'Eloqua', 'India', '$2a$12$placeholder_hash_for_Eloqua@2026', 'user', 1, NOW()),
('kabir', 'mishra', 'kabir.mishra25@outlook.com', 'User', 'Freshworks', 'India', '$2a$12$placeholder_hash_for_Freshworks@2026', 'user', 1, NOW()),
('aditya', 'chopra', 'aditya.chopra4@outlook.com', 'User', 'HubSpot', 'India', '$2a$12$placeholder_hash_for_HubSpot@2026', 'user', 1, NOW()),
('raj', 'khanna', 'raj.khanna40@company.com', 'User', 'HubSpot', 'India', '$2a$12$placeholder_hash_for_HubSpot@2026', 'user', 1, NOW()),
('vivaan', 'bhatia', 'vivaan.bhatia21@company.com', 'User', 'HubSpot', 'India', '$2a$12$placeholder_hash_for_HubSpot@2026', 'user', 1, NOW()),
('kiaan', 'jain', 'kiaan.jain5@yahoo.com', 'User', 'Infusionsoft', 'India', '$2a$12$placeholder_hash_for_Infusionsoft@2026', 'user', 1, NOW()),
('saanvi', 'kaur', 'saanvi.kaur32@yahoo.com', 'User', 'Infusionsoft', 'India', '$2a$12$placeholder_hash_for_Infusionsoft@2026', 'user', 1, NOW()),
('aarav', 'pandey', 'aarav.pandey23@outlook.com', 'User', 'Insightly', 'India', '$2a$12$placeholder_hash_for_Insightly@2026', 'user', 1, NOW()),
('raj', 'menon', 'raj.menon11@outlook.com', 'User', 'Insightly', 'India', '$2a$12$placeholder_hash_for_Insightly@2026', 'user', 1, NOW()),
('vivaan', 'das', 'vivaan.das15@company.com', 'User', 'Insightly', 'India', '$2a$12$placeholder_hash_for_Insightly@2026', 'user', 1, NOW()),
('meera', 'shukla', 'meera.shukla29@hotmail.com', 'User', 'Lattice Engines', 'India', '$2a$12$placeholder_hash_for_LatticeEngines@2026', 'user', 1, NOW()),
('aditya', 'shah', 'aditya.shah17@hotmail.com', 'User', 'LeadSquared', 'India', '$2a$12$placeholder_hash_for_LeadSquared@2026', 'user', 1, NOW()),
('veer', 'tiwari', 'veer.tiwari24@gmail.com', 'User', 'LeadSquared', 'India', '$2a$12$placeholder_hash_for_LeadSquared@2026', 'user', 1, NOW()),
('veer', 'reddy', 'veer.reddy38@company.com', 'User', 'LeadSquared', 'India', '$2a$12$placeholder_hash_for_LeadSquared@2026', 'user', 1, NOW()),
('kiaan', 'jain', 'kiaan.jain14@company.com', 'User', 'Marketo', 'India', '$2a$12$placeholder_hash_for_Marketo@2026', 'user', 1, NOW()),
('rohan', 'kapoor', 'rohan.kapoor9@gmail.com', 'User', 'Marketo', 'India', '$2a$12$placeholder_hash_for_Marketo@2026', 'user', 1, NOW()),
('aditi', 'malhotra', 'aditi.malhotra33@yahoo.com', 'User', 'Oracle Marketing Cloud', 'India', '$2a$12$placeholder_hash_for_OracleMarketingCloud@2026', 'user', 1, NOW()),
('arjun', 'tiwari', 'arjun.tiwari2@hotmail.com', 'User', 'Outreach', 'India', '$2a$12$placeholder_hash_for_Outreach@2026', 'user', 1, NOW()),
('ananya', 'reddy', 'ananya.reddy16@outlook.com', 'User', 'Pardot', 'India', '$2a$12$placeholder_hash_for_Pardot@2026', 'user', 1, NOW()),
('diya', 'verma', 'diya.verma20@hotmail.com', 'User', 'Salesforce', 'India', '$2a$12$placeholder_hash_for_Salesforce@2026', 'user', 1, NOW()),
('aditya', 'kumar', 'aditya.kumar31@outlook.com', 'User', 'Salesfusion', 'India', '$2a$12$placeholder_hash_for_Salesfusion@2026', 'user', 1, NOW()),
('raj', 'reddy', 'raj.reddy18@gmail.com', 'User', 'Salesfusion', 'India', '$2a$12$placeholder_hash_for_Salesfusion@2026', 'user', 1, NOW()),
('meera', 'kapoor', 'meera.kapoor37@outlook.com', 'User', 'Woodpecker', 'India', '$2a$12$placeholder_hash_for_Woodpecker@2026', 'user', 1, NOW()),
('vihaan', 'menon', 'vihaan.menon22@outlook.com', 'User', 'Woodpecker', 'India', '$2a$12$placeholder_hash_for_Woodpecker@2026', 'user', 1, NOW()),
('advik', 'pandey', 'advik.pandey19@yahoo.com', 'User', 'Zoho', 'India', '$2a$12$placeholder_hash_for_Zoho@2026', 'user', 1, NOW()),
('ananya', 'bhatia', 'ananya.bhatia8@company.com', 'User', 'Zoho', 'India', '$2a$12$placeholder_hash_for_Zoho@2026', 'user', 1, NOW()),
('anita', 'tiwari', 'anita.tiwari7@hotmail.com', 'User', 'Zoho', 'India', '$2a$12$placeholder_hash_for_Zoho@2026', 'user', 1, NOW()),
('kabir', 'singh', 'kabir.singh36@outlook.com', 'User', 'Zoho', 'India', '$2a$12$placeholder_hash_for_Zoho@2026', 'user', 1, NOW()),
('aditi', 'reddy', 'aditi.reddy26@yahoo.com', 'User', 'ZoomInfo', 'India', '$2a$12$placeholder_hash_for_ZoomInfo@2026', 'user', 1, NOW()),
('haruki', 'kojima', 'haruki.kojima10@gmail.com', 'User', '6sense Japan', 'Japan', '$2a$12$placeholder_hash_for_6senseJapan@2026', 'user', 1, NOW()),
('kanon', 'suzuki', 'kanon.suzuki15@outlook.com', 'User', '6sense Japan', 'Japan', '$2a$12$placeholder_hash_for_6senseJapan@2026', 'user', 1, NOW()),
('koki', 'watanabe', 'koki.watanabe19@company.com', 'User', '6sense Japan', 'Japan', '$2a$12$placeholder_hash_for_6senseJapan@2026', 'user', 1, NOW()),
('nozomi', 'fujita', 'nozomi.fujita62@yahoo.com', 'User', '6sense Japan', 'Japan', '$2a$12$placeholder_hash_for_6senseJapan@2026', 'user', 1, NOW()),
('ayaka', 'murakami', 'ayaka.murakami11@yahoo.com', 'User', 'Act-On Japan', 'Japan', '$2a$12$placeholder_hash_for_Act-OnJapan@2026', 'user', 1, NOW()),
('sakura', 'koyama', 'sakura.koyama14@gmail.com', 'User', 'Act-On Japan', 'Japan', '$2a$12$placeholder_hash_for_Act-OnJapan@2026', 'user', 1, NOW()),
('yuna', 'kudo', 'yuna.kudo21@hotmail.com', 'User', 'Act-On Japan', 'Japan', '$2a$12$placeholder_hash_for_Act-OnJapan@2026', 'user', 1, NOW()),
('haruki', 'yamamoto', 'haruki.yamamoto44@gmail.com', 'User', 'Adobe Marketo Japan', 'Japan', '$2a$12$placeholder_hash_for_AdobeMarketoJapan@2026', 'user', 1, NOW()),
('rin', 'sasaki', 'rin.sasaki52@hotmail.com', 'User', 'Adobe Marketo Japan', 'Japan', '$2a$12$placeholder_hash_for_AdobeMarketoJapan@2026', 'user', 1, NOW()),
('yume', 'fukuda', 'yume.fukuda53@company.com', 'User', 'Adobe Marketo Japan', 'Japan', '$2a$12$placeholder_hash_for_AdobeMarketoJapan@2026', 'user', 1, NOW()),
('saki', 'watanabe', 'saki.watanabe28@company.com', 'User', 'Autopilot Japan', 'Japan', '$2a$12$placeholder_hash_for_AutopilotJapan@2026', 'user', 1, NOW()),
('yuki', 'ota', 'yuki.ota30@company.com', 'User', 'Autopilot Japan', 'Japan', '$2a$12$placeholder_hash_for_AutopilotJapan@2026', 'user', 1, NOW()),
('yuki', 'mori', 'yuki.mori33@company.com', 'User', 'Autopilot Japan', 'Japan', '$2a$12$placeholder_hash_for_AutopilotJapan@2026', 'user', 1, NOW()),
('yua', 'tanaka', 'yua.tanaka31@outlook.com', 'User', 'Bombora Japan', 'Japan', '$2a$12$placeholder_hash_for_BomboraJapan@2026', 'user', 1, NOW()),
('sora', 'yamamoto', 'sora.yamamoto34@gmail.com', 'User', 'Clearbit Japan', 'Japan', '$2a$12$placeholder_hash_for_ClearbitJapan@2026', 'user', 1, NOW()),
('yui', 'yamamoto', 'yui.yamamoto29@gmail.com', 'User', 'Clearbit Japan', 'Japan', '$2a$12$placeholder_hash_for_ClearbitJapan@2026', 'user', 1, NOW()),
('koki', 'okamoto', 'koki.okamoto2@outlook.com', 'User', 'Demandbase Japan', 'Japan', '$2a$12$placeholder_hash_for_DemandbaseJapan@2026', 'user', 1, NOW()),
('ren', 'kojima', 'ren.kojima61@hotmail.com', 'User', 'Drip Japan', 'Japan', '$2a$12$placeholder_hash_for_DripJapan@2026', 'user', 1, NOW()),
('kanon', 'takahashi', 'kanon.takahashi8@company.com', 'User', 'Dun & Bradstreet Japan', 'Japan', '$2a$12$placeholder_hash_for_Dun&BradstreetJapan@2026', 'user', 1, NOW()),
('rin', 'tanaka', 'rin.tanaka17@company.com', 'User', 'Dun & Bradstreet Japan', 'Japan', '$2a$12$placeholder_hash_for_Dun&BradstreetJapan@2026', 'user', 1, NOW()),
('sora', 'fujiwara', 'sora.fujiwara9@outlook.com', 'User', 'Dun & Bradstreet Japan', 'Japan', '$2a$12$placeholder_hash_for_Dun&BradstreetJapan@2026', 'user', 1, NOW()),
('anju', 'murakami', 'anju.murakami63@gmail.com', 'User', 'Eloqua Japan', 'Japan', '$2a$12$placeholder_hash_for_EloquaJapan@2026', 'user', 1, NOW()),
('rin', 'miura', 'rin.miura27@hotmail.com', 'User', 'Eloqua Japan', 'Japan', '$2a$12$placeholder_hash_for_EloquaJapan@2026', 'user', 1, NOW()),
('hina', 'suzuki', 'hina.suzuki54@outlook.com', 'User', 'Freshworks Japan', 'Japan', '$2a$12$placeholder_hash_for_FreshworksJapan@2026', 'user', 1, NOW()),
('koharu', 'okamoto', 'koharu.okamoto7@gmail.com', 'User', 'HubSpot Japan', 'Japan', '$2a$12$placeholder_hash_for_HubSpotJapan@2026', 'user', 1, NOW()),
('rina', 'murakami', 'rina.murakami42@gmail.com', 'User', 'HubSpot Japan', 'Japan', '$2a$12$placeholder_hash_for_HubSpotJapan@2026', 'user', 1, NOW()),
('aoi', 'yamada', 'aoi.yamada48@company.com', 'User', 'Infusionsoft Japan', 'Japan', '$2a$12$placeholder_hash_for_InfusionsoftJapan@2026', 'user', 1, NOW()),
('hina', 'hasegawa', 'hina.hasegawa56@gmail.com', 'User', 'Infusionsoft Japan', 'Japan', '$2a$12$placeholder_hash_for_InfusionsoftJapan@2026', 'user', 1, NOW()),
('koki', 'kimura', 'koki.kimura37@gmail.com', 'User', 'Insightly Japan', 'Japan', '$2a$12$placeholder_hash_for_InsightlyJapan@2026', 'user', 1, NOW()),
('kokone', 'kobayashi', 'kokone.kobayashi1@gmail.com', 'User', 'Insightly Japan', 'Japan', '$2a$12$placeholder_hash_for_InsightlyJapan@2026', 'user', 1, NOW()),
('haruki', 'fukuda', 'haruki.fukuda58@company.com', 'User', 'Lattice Engines Japan', 'Japan', '$2a$12$placeholder_hash_for_LatticeEnginesJapan@2026', 'user', 1, NOW()),
('haruto', 'koyama', 'haruto.koyama5@yahoo.com', 'User', 'Lattice Engines Japan', 'Japan', '$2a$12$placeholder_hash_for_LatticeEnginesJapan@2026', 'user', 1, NOW()),
('karen', 'fukuda', 'karen.fukuda20@yahoo.com', 'User', 'Lattice Engines Japan', 'Japan', '$2a$12$placeholder_hash_for_LatticeEnginesJapan@2026', 'user', 1, NOW()),
('rina', 'ota', 'rina.ota39@outlook.com', 'User', 'Lattice Engines Japan', 'Japan', '$2a$12$placeholder_hash_for_LatticeEnginesJapan@2026', 'user', 1, NOW()),
('sora', 'fujiwara', 'sora.fujiwara18@gmail.com', 'User', 'Lattice Engines Japan', 'Japan', '$2a$12$placeholder_hash_for_LatticeEnginesJapan@2026', 'user', 1, NOW()),
('suzu', 'miura', 'suzu.miura40@gmail.com', 'User', 'Lattice Engines Japan', 'Japan', '$2a$12$placeholder_hash_for_LatticeEnginesJapan@2026', 'user', 1, NOW()),
('suzu', 'kimura', 'suzu.kimura47@hotmail.com', 'User', 'LeadFeeder Japan', 'Japan', '$2a$12$placeholder_hash_for_LeadFeederJapan@2026', 'user', 1, NOW()),
('hina', 'kojima', 'hina.kojima59@hotmail.com', 'User', 'LeadSquared Japan', 'Japan', '$2a$12$placeholder_hash_for_LeadSquaredJapan@2026', 'user', 1, NOW()),
('sota', 'hasegawa', 'sota.hasegawa36@hotmail.com', 'User', 'LeadSquared Japan', 'Japan', '$2a$12$placeholder_hash_for_LeadSquaredJapan@2026', 'user', 1, NOW()),
('yuto', 'tanaka', 'yuto.tanaka12@gmail.com', 'User', 'LeadSquared Japan', 'Japan', '$2a$12$placeholder_hash_for_LeadSquaredJapan@2026', 'user', 1, NOW()),
('aoi', 'goto', 'aoi.goto24@yahoo.com', 'User', 'Marketo Japan', 'Japan', '$2a$12$placeholder_hash_for_MarketoJapan@2026', 'user', 1, NOW()),
('misaki', 'kimura', 'misaki.kimura38@hotmail.com', 'User', 'Marketo Japan', 'Japan', '$2a$12$placeholder_hash_for_MarketoJapan@2026', 'user', 1, NOW()),
('riko', 'sasaki', 'riko.sasaki25@gmail.com', 'User', 'Marketo Japan', 'Japan', '$2a$12$placeholder_hash_for_MarketoJapan@2026', 'user', 1, NOW()),
('mei', 'sato', 'mei.sato60@hotmail.com', 'User', 'Oracle Marketing Cloud Japan', 'Japan', '$2a$12$placeholder_hash_for_OracleMarketingCloudJapan@2026', 'user', 1, NOW()),
('riko', 'inoue', 'riko.inoue13@gmail.com', 'User', 'Outreach Japan', 'Japan', '$2a$12$placeholder_hash_for_OutreachJapan@2026', 'user', 1, NOW()),
('rira', 'miura', 'rira.miura3@company.com', 'User', 'Outreach Japan', 'Japan', '$2a$12$placeholder_hash_for_OutreachJapan@2026', 'user', 1, NOW()),
('sakura', 'ota', 'sakura.ota45@hotmail.com', 'User', 'Outreach Japan', 'Japan', '$2a$12$placeholder_hash_for_OutreachJapan@2026', 'user', 1, NOW()),
('suzu', 'murakami', 'suzu.murakami22@gmail.com', 'User', 'Outreach Japan', 'Japan', '$2a$12$placeholder_hash_for_OutreachJapan@2026', 'user', 1, NOW()),
('kanon', 'miura', 'kanon.miura41@yahoo.com', 'User', 'Pardot Japan', 'Japan', '$2a$12$placeholder_hash_for_PardotJapan@2026', 'user', 1, NOW()),
('koharu', 'okamoto', 'koharu.okamoto50@company.com', 'User', 'Pardot Japan', 'Japan', '$2a$12$placeholder_hash_for_PardotJapan@2026', 'user', 1, NOW()),
('mei', 'tanaka', 'mei.tanaka32@yahoo.com', 'User', 'Pardot Japan', 'Japan', '$2a$12$placeholder_hash_for_PardotJapan@2026', 'user', 1, NOW()),
('nanami', 'nakamura', 'nanami.nakamura35@gmail.com', 'User', 'Salesforce Japan', 'Japan', '$2a$12$placeholder_hash_for_SalesforceJapan@2026', 'user', 1, NOW()),
('yuna', 'sato', 'yuna.sato64@hotmail.com', 'User', 'Salesforce Japan', 'Japan', '$2a$12$placeholder_hash_for_SalesforceJapan@2026', 'user', 1, NOW()),
('miyu', 'okamoto', 'miyu.okamoto4@outlook.com', 'User', 'Salesfusion Japan', 'Japan', '$2a$12$placeholder_hash_for_SalesfusionJapan@2026', 'user', 1, NOW()),
('rin', 'inoue', 'rin.inoue55@outlook.com', 'User', 'Salesfusion Japan', 'Japan', '$2a$12$placeholder_hash_for_SalesfusionJapan@2026', 'user', 1, NOW()),
('yume', 'yamaguchi', 'yume.yamaguchi51@yahoo.com', 'User', 'Salesfusion Japan', 'Japan', '$2a$12$placeholder_hash_for_SalesfusionJapan@2026', 'user', 1, NOW()),
('kokone', 'takahashi', 'kokone.takahashi26@gmail.com', 'User', 'SharpSpring Japan', 'Japan', '$2a$12$placeholder_hash_for_SharpSpringJapan@2026', 'user', 1, NOW()),
('hina', 'goto', 'hina.goto6@company.com', 'User', 'Woodpecker Japan', 'Japan', '$2a$12$placeholder_hash_for_WoodpeckerJapan@2026', 'user', 1, NOW()),
('misaki', 'sasaki', 'misaki.sasaki49@yahoo.com', 'User', 'Woodpecker Japan', 'Japan', '$2a$12$placeholder_hash_for_WoodpeckerJapan@2026', 'user', 1, NOW()),
('miyu', 'yamaguchi', 'miyu.yamaguchi43@yahoo.com', 'User', 'Woodpecker Japan', 'Japan', '$2a$12$placeholder_hash_for_WoodpeckerJapan@2026', 'user', 1, NOW()),
('aoi', 'kudo', 'aoi.kudo23@yahoo.com', 'User', 'Zoho Japan', 'Japan', '$2a$12$placeholder_hash_for_ZohoJapan@2026', 'user', 1, NOW()),
('koharu', 'sasaki', 'koharu.sasaki57@hotmail.com', 'User', 'Zoho Japan', 'Japan', '$2a$12$placeholder_hash_for_ZohoJapan@2026', 'user', 1, NOW()),
('koki', 'mori', 'koki.mori16@hotmail.com', 'User', 'Zoho Japan', 'Japan', '$2a$12$placeholder_hash_for_ZohoJapan@2026', 'user', 1, NOW()),
('riko', 'inoue', 'riko.inoue46@outlook.com', 'User', 'ZoomInfo Japan', 'Japan', '$2a$12$placeholder_hash_for_ZoomInfoJapan@2026', 'user', 1, NOW()),
('amelia', 'jackson', 'amelia.jackson26@gmail.com', 'User', '6sense UK', 'United Kingdom', '$2a$12$placeholder_hash_for_6senseUK@2026', 'user', 1, NOW()),
('esme', 'clarke', 'esme.clarke47@yahoo.com', 'User', '6sense UK', 'United Kingdom', '$2a$12$placeholder_hash_for_6senseUK@2026', 'user', 1, NOW()),
('willow', 'roberts', 'willow.roberts7@gmail.com', 'User', '6sense UK', 'United Kingdom', '$2a$12$placeholder_hash_for_6senseUK@2026', 'user', 1, NOW()),
('oliver', 'evans', 'oliver.evans46@company.com', 'User', 'Act-On UK', 'United Kingdom', '$2a$12$placeholder_hash_for_Act-OnUK@2026', 'user', 1, NOW()),
('ava', 'martin', 'ava.martin44@hotmail.com', 'User', 'Adobe Marketo UK', 'United Kingdom', '$2a$12$placeholder_hash_for_AdobeMarketoUK@2026', 'user', 1, NOW()),
('harry', 'clarke', 'harry.clarke39@yahoo.com', 'User', 'Adobe Marketo UK', 'United Kingdom', '$2a$12$placeholder_hash_for_AdobeMarketoUK@2026', 'user', 1, NOW()),
('lily', 'jackson', 'lily.jackson21@company.com', 'User', 'Adobe Marketo UK', 'United Kingdom', '$2a$12$placeholder_hash_for_AdobeMarketoUK@2026', 'user', 1, NOW()),
('amelia', 'west', 'amelia.west13@company.com', 'User', 'Autopilot UK', 'United Kingdom', '$2a$12$placeholder_hash_for_AutopilotUK@2026', 'user', 1, NOW()),
('ava', 'brown', 'ava.brown37@outlook.com', 'User', 'Autopilot UK', 'United Kingdom', '$2a$12$placeholder_hash_for_AutopilotUK@2026', 'user', 1, NOW()),
('freya', 'roberts', 'freya.roberts34@outlook.com', 'User', 'Autopilot UK', 'United Kingdom', '$2a$12$placeholder_hash_for_AutopilotUK@2026', 'user', 1, NOW()),
('mia', 'roberts', 'mia.roberts22@gmail.com', 'User', 'Bombora UK', 'United Kingdom', '$2a$12$placeholder_hash_for_BomboraUK@2026', 'user', 1, NOW()),
('theo', 'clarke', 'theo.clarke2@outlook.com', 'User', 'Bombora UK', 'United Kingdom', '$2a$12$placeholder_hash_for_BomboraUK@2026', 'user', 1, NOW()),
('evelyn', 'brown', 'evelyn.brown17@yahoo.com', 'User', 'Clearbit UK', 'United Kingdom', '$2a$12$placeholder_hash_for_ClearbitUK@2026', 'user', 1, NOW()),
('ivy', 'martin', 'ivy.martin58@yahoo.com', 'User', 'Clearbit UK', 'United Kingdom', '$2a$12$placeholder_hash_for_ClearbitUK@2026', 'user', 1, NOW()),
('layla', 'roberts', 'layla.roberts29@gmail.com', 'User', 'Clearbit UK', 'United Kingdom', '$2a$12$placeholder_hash_for_ClearbitUK@2026', 'user', 1, NOW()),
('olivia', 'king', 'olivia.king40@yahoo.com', 'User', 'Clearbit UK', 'United Kingdom', '$2a$12$placeholder_hash_for_ClearbitUK@2026', 'user', 1, NOW()),
('poppy', 'lee', 'poppy.lee54@company.com', 'User', 'Clearbit UK', 'United Kingdom', '$2a$12$placeholder_hash_for_ClearbitUK@2026', 'user', 1, NOW()),
('ruby', 'brown', 'ruby.brown33@outlook.com', 'User', 'Clearbit UK', 'United Kingdom', '$2a$12$placeholder_hash_for_ClearbitUK@2026', 'user', 1, NOW()),
('theo', 'west', 'theo.west11@company.com', 'User', 'Clearbit UK', 'United Kingdom', '$2a$12$placeholder_hash_for_ClearbitUK@2026', 'user', 1, NOW()),
('rosie', 'west', 'rosie.west59@yahoo.com', 'User', 'Demandbase UK', 'United Kingdom', '$2a$12$placeholder_hash_for_DemandbaseUK@2026', 'user', 1, NOW()),
('charlotte', 'jackson', 'charlotte.jackson10@outlook.com', 'User', 'Drip UK', 'United Kingdom', '$2a$12$placeholder_hash_for_DripUK@2026', 'user', 1, NOW()),
('willow', 'thompson', 'willow.thompson51@hotmail.com', 'User', 'Drip UK', 'United Kingdom', '$2a$12$placeholder_hash_for_DripUK@2026', 'user', 1, NOW()),
('charlie', 'clarke', 'charlie.clarke35@outlook.com', 'User', 'Dun & Bradstreet UK', 'United Kingdom', '$2a$12$placeholder_hash_for_Dun&BradstreetUK@2026', 'user', 1, NOW()),
('ivy', 'martin', 'ivy.martin3@hotmail.com', 'User', 'Dun & Bradstreet UK', 'United Kingdom', '$2a$12$placeholder_hash_for_Dun&BradstreetUK@2026', 'user', 1, NOW()),
('noah', 'jones', 'noah.jones6@company.com', 'User', 'Dun & Bradstreet UK', 'United Kingdom', '$2a$12$placeholder_hash_for_Dun&BradstreetUK@2026', 'user', 1, NOW()),
('noah', 'king', 'noah.king12@company.com', 'User', 'Freshworks UK', 'United Kingdom', '$2a$12$placeholder_hash_for_FreshworksUK@2026', 'user', 1, NOW()),
('theo', 'white', 'theo.white36@outlook.com', 'User', 'Freshworks UK', 'United Kingdom', '$2a$12$placeholder_hash_for_FreshworksUK@2026', 'user', 1, NOW()),
('evelyn', 'smith', 'evelyn.smith56@outlook.com', 'User', 'HubSpot UK', 'United Kingdom', '$2a$12$placeholder_hash_for_HubSpotUK@2026', 'user', 1, NOW()),
('isla', 'morgan', 'isla.morgan41@yahoo.com', 'User', 'Infusionsoft UK', 'United Kingdom', '$2a$12$placeholder_hash_for_InfusionsoftUK@2026', 'user', 1, NOW()),
('scarlett', 'walker', 'scarlett.walker28@outlook.com', 'User', 'Infusionsoft UK', 'United Kingdom', '$2a$12$placeholder_hash_for_InfusionsoftUK@2026', 'user', 1, NOW()),
('charlotte', 'wilson', 'charlotte.wilson25@company.com', 'User', 'Insightly UK', 'United Kingdom', '$2a$12$placeholder_hash_for_InsightlyUK@2026', 'user', 1, NOW()),
('freya', 'cooper', 'freya.cooper52@yahoo.com', 'User', 'Insightly UK', 'United Kingdom', '$2a$12$placeholder_hash_for_InsightlyUK@2026', 'user', 1, NOW()),
('isla', 'clarke', 'isla.clarke42@yahoo.com', 'User', 'Insightly UK', 'United Kingdom', '$2a$12$placeholder_hash_for_InsightlyUK@2026', 'user', 1, NOW()),
('leo', 'robinson', 'leo.robinson20@company.com', 'User', 'Insightly UK', 'United Kingdom', '$2a$12$placeholder_hash_for_InsightlyUK@2026', 'user', 1, NOW()),
('lily', 'jackson', 'lily.jackson38@hotmail.com', 'User', 'Insightly UK', 'United Kingdom', '$2a$12$placeholder_hash_for_InsightlyUK@2026', 'user', 1, NOW()),
('amelia', 'wood', 'amelia.wood4@hotmail.com', 'User', 'LeadFeeder UK', 'United Kingdom', '$2a$12$placeholder_hash_for_LeadFeederUK@2026', 'user', 1, NOW()),
('sienna', 'lee', 'sienna.lee60@hotmail.com', 'User', 'LeadFeeder UK', 'United Kingdom', '$2a$12$placeholder_hash_for_LeadFeederUK@2026', 'user', 1, NOW()),
('layla', 'brown', 'layla.brown53@hotmail.com', 'User', 'LeadSquared UK', 'United Kingdom', '$2a$12$placeholder_hash_for_LeadSquaredUK@2026', 'user', 1, NOW()),
('emily', 'brown', 'emily.brown55@hotmail.com', 'User', 'Marketo UK', 'United Kingdom', '$2a$12$placeholder_hash_for_MarketoUK@2026', 'user', 1, NOW()),
('esme', 'johnson', 'esme.johnson30@gmail.com', 'User', 'Marketo UK', 'United Kingdom', '$2a$12$placeholder_hash_for_MarketoUK@2026', 'user', 1, NOW()),
('harper', 'brown', 'harper.brown8@gmail.com', 'User', 'Oracle Marketing Cloud UK', 'United Kingdom', '$2a$12$placeholder_hash_for_OracleMarketingCloudUK@2026', 'user', 1, NOW()),
('maisy', 'watson', 'maisy.watson50@yahoo.com', 'User', 'Oracle Marketing Cloud UK', 'United Kingdom', '$2a$12$placeholder_hash_for_OracleMarketingCloudUK@2026', 'user', 1, NOW()),
('ruby', 'cooper', 'ruby.cooper49@outlook.com', 'User', 'Oracle Marketing Cloud UK', 'United Kingdom', '$2a$12$placeholder_hash_for_OracleMarketingCloudUK@2026', 'user', 1, NOW()),
('ella', 'taylor', 'ella.taylor23@yahoo.com', 'User', 'Outreach UK', 'United Kingdom', '$2a$12$placeholder_hash_for_OutreachUK@2026', 'user', 1, NOW()),
('grace', 'martin', 'grace.martin15@outlook.com', 'User', 'Pardot UK', 'United Kingdom', '$2a$12$placeholder_hash_for_PardotUK@2026', 'user', 1, NOW()),
('jack', 'thomas', 'jack.thomas18@yahoo.com', 'User', 'Pardot UK', 'United Kingdom', '$2a$12$placeholder_hash_for_PardotUK@2026', 'user', 1, NOW()),
('mia', 'white', 'mia.white31@gmail.com', 'User', 'Pardot UK', 'United Kingdom', '$2a$12$placeholder_hash_for_PardotUK@2026', 'user', 1, NOW()),
('esme', 'martin', 'esme.martin19@yahoo.com', 'User', 'Salesforce UK', 'United Kingdom', '$2a$12$placeholder_hash_for_SalesforceUK@2026', 'user', 1, NOW()),
('ivy', 'jones', 'ivy.jones57@yahoo.com', 'User', 'Salesforce UK', 'United Kingdom', '$2a$12$placeholder_hash_for_SalesforceUK@2026', 'user', 1, NOW()),
('isla', 'brown', 'isla.brown43@gmail.com', 'User', 'Salesfusion UK', 'United Kingdom', '$2a$12$placeholder_hash_for_SalesfusionUK@2026', 'user', 1, NOW()),
('noah', 'johnson', 'noah.johnson24@outlook.com', 'User', 'Salesfusion UK', 'United Kingdom', '$2a$12$placeholder_hash_for_SalesfusionUK@2026', 'user', 1, NOW()),
('sienna', 'harris', 'sienna.harris16@outlook.com', 'User', 'Salesfusion UK', 'United Kingdom', '$2a$12$placeholder_hash_for_SalesfusionUK@2026', 'user', 1, NOW()),
('sophie', 'morgan', 'sophie.morgan32@hotmail.com', 'User', 'Salesfusion UK', 'United Kingdom', '$2a$12$placeholder_hash_for_SalesfusionUK@2026', 'user', 1, NOW()),
('isabella', 'wright', 'isabella.wright45@yahoo.com', 'User', 'SharpSpring UK', 'United Kingdom', '$2a$12$placeholder_hash_for_SharpSpringUK@2026', 'user', 1, NOW()),
('ivy', 'west', 'ivy.west14@company.com', 'User', 'SharpSpring UK', 'United Kingdom', '$2a$12$placeholder_hash_for_SharpSpringUK@2026', 'user', 1, NOW()),
('sophia', 'evans', 'sophia.evans48@outlook.com', 'User', 'SharpSpring UK', 'United Kingdom', '$2a$12$placeholder_hash_for_SharpSpringUK@2026', 'user', 1, NOW()),
('emily', 'west', 'emily.west27@outlook.com', 'User', 'Woodpecker UK', 'United Kingdom', '$2a$12$placeholder_hash_for_WoodpeckerUK@2026', 'user', 1, NOW()),
('oliver', 'edwards', 'oliver.edwards1@hotmail.com', 'User', 'Woodpecker UK', 'United Kingdom', '$2a$12$placeholder_hash_for_WoodpeckerUK@2026', 'user', 1, NOW()),
('emily', 'roberts', 'emily.roberts9@company.com', 'User', 'Zoho UK', 'United Kingdom', '$2a$12$placeholder_hash_for_ZohoUK@2026', 'user', 1, NOW()),
('jack', 'morgan', 'jack.morgan5@hotmail.com', 'User', 'Zoho UK', 'United Kingdom', '$2a$12$placeholder_hash_for_ZohoUK@2026', 'user', 1, NOW()),
('emily', 'robinson', 'emily.robinson20@hotmail.com', 'User', '6sense', 'United States', '$2a$12$placeholder_hash_for_6sense@2026', 'user', 1, NOW()),
('richard', 'ramirez', 'richard.ramirez15@outlook.com', 'User', '6sense', 'United States', '$2a$12$placeholder_hash_for_6sense@2026', 'user', 1, NOW()),
('karen', 'thomas', 'karen.thomas27@gmail.com', 'User', 'Act-On', 'United States', '$2a$12$placeholder_hash_for_Act-On@2026', 'user', 1, NOW()),
('margaret', 'robinson', 'margaret.robinson40@hotmail.com', 'User', 'Adobe Marketo', 'United States', '$2a$12$placeholder_hash_for_AdobeMarketo@2026', 'user', 1, NOW()),
('susan', 'wilson', 'susan.wilson42@company.com', 'User', 'Adobe Marketo', 'United States', '$2a$12$placeholder_hash_for_AdobeMarketo@2026', 'user', 1, NOW()),
('melissa', 'martinez', 'melissa.martinez49@yahoo.com', 'User', 'Autopilot', 'United States', '$2a$12$placeholder_hash_for_Autopilot@2026', 'user', 1, NOW()),
('robert', 'lopez', 'robert.lopez70@hotmail.com', 'User', 'Autopilot', 'United States', '$2a$12$placeholder_hash_for_Autopilot@2026', 'user', 1, NOW()),
('barbara', 'sanchez', 'barbara.sanchez19@hotmail.com', 'User', 'Bombora', 'United States', '$2a$12$placeholder_hash_for_Bombora@2026', 'user', 1, NOW()),
('charles', 'white', 'charles.white45@hotmail.com', 'User', 'Bombora', 'United States', '$2a$12$placeholder_hash_for_Bombora@2026', 'user', 1, NOW()),
('margaret', 'brown', 'margaret.brown3@gmail.com', 'User', 'Bombora', 'United States', '$2a$12$placeholder_hash_for_Bombora@2026', 'user', 1, NOW()),
('sarah', 'lewis', 'sarah.lewis7@company.com', 'User', 'Bombora', 'United States', '$2a$12$placeholder_hash_for_Bombora@2026', 'user', 1, NOW()),
('john', 'robinson', 'john.robinson29@company.com', 'User', 'Calendly', 'United States', '$2a$12$placeholder_hash_for_Calendly@2026', 'user', 1, NOW()),
('michelle', 'perez', 'michelle.perez37@outlook.com', 'User', 'Calendly', 'United States', '$2a$12$placeholder_hash_for_Calendly@2026', 'user', 1, NOW()),
('deborah', 'lewis', 'deborah.lewis56@gmail.com', 'User', 'Clearbit', 'United States', '$2a$12$placeholder_hash_for_Clearbit@2026', 'user', 1, NOW()),
('deborah', 'lee', 'deborah.lee68@outlook.com', 'User', 'Clearbit', 'United States', '$2a$12$placeholder_hash_for_Clearbit@2026', 'user', 1, NOW()),
('donna', 'white', 'donna.white17@outlook.com', 'User', 'Clearbit', 'United States', '$2a$12$placeholder_hash_for_Clearbit@2026', 'user', 1, NOW()),
('kimberly', 'robinson', 'kimberly.robinson25@company.com', 'User', 'Clearbit', 'United States', '$2a$12$placeholder_hash_for_Clearbit@2026', 'user', 1, NOW()),
('dorothy', 'thompson', 'dorothy.thompson48@gmail.com', 'User', 'Demandbase', 'United States', '$2a$12$placeholder_hash_for_Demandbase@2026', 'user', 1, NOW()),
('betty', 'robinson', 'betty.robinson28@outlook.com', 'User', 'Drift', 'United States', '$2a$12$placeholder_hash_for_Drift@2026', 'user', 1, NOW()),
('donna', 'perez', 'donna.perez69@yahoo.com', 'User', 'Drift', 'United States', '$2a$12$placeholder_hash_for_Drift@2026', 'user', 1, NOW()),
('jessica', 'anderson', 'jessica.anderson1@company.com', 'User', 'Drift', 'United States', '$2a$12$placeholder_hash_for_Drift@2026', 'user', 1, NOW()),
('karen', 'williams', 'karen.williams72@outlook.com', 'User', 'Drift', 'United States', '$2a$12$placeholder_hash_for_Drift@2026', 'user', 1, NOW()),
('kimberly', 'hernandez', 'kimberly.hernandez46@yahoo.com', 'User', 'Drift', 'United States', '$2a$12$placeholder_hash_for_Drift@2026', 'user', 1, NOW()),
('lisa', 'sanchez', 'lisa.sanchez74@company.com', 'User', 'Drift', 'United States', '$2a$12$placeholder_hash_for_Drift@2026', 'user', 1, NOW()),
('amanda', 'martin', 'amanda.martin9@outlook.com', 'User', 'Drip', 'United States', '$2a$12$placeholder_hash_for_Drip@2026', 'user', 1, NOW()),
('james', 'perez', 'james.perez26@company.com', 'User', 'Drip', 'United States', '$2a$12$placeholder_hash_for_Drip@2026', 'user', 1, NOW()),
('melissa', 'thomas', 'melissa.thomas35@yahoo.com', 'User', 'Drip', 'United States', '$2a$12$placeholder_hash_for_Drip@2026', 'user', 1, NOW()),
('thomas', 'lopez', 'thomas.lopez8@outlook.com', 'User', 'Drip', 'United States', '$2a$12$placeholder_hash_for_Drip@2026', 'user', 1, NOW()),
('donna', 'white', 'donna.white60@outlook.com', 'User', 'Dun & Bradstreet', 'United States', '$2a$12$placeholder_hash_for_Dun&Bradstreet@2026', 'user', 1, NOW()),
('margaret', 'jones', 'margaret.jones50@gmail.com', 'User', 'Dun & Bradstreet', 'United States', '$2a$12$placeholder_hash_for_Dun&Bradstreet@2026', 'user', 1, NOW()),
('carol', 'anderson', 'carol.anderson24@gmail.com', 'User', 'Eloqua', 'United States', '$2a$12$placeholder_hash_for_Eloqua@2026', 'user', 1, NOW()),
('kimberly', 'perez', 'kimberly.perez59@hotmail.com', 'User', 'Eloqua', 'United States', '$2a$12$placeholder_hash_for_Eloqua@2026', 'user', 1, NOW()),
('richard', 'thomas', 'richard.thomas16@company.com', 'User', 'Eloqua', 'United States', '$2a$12$placeholder_hash_for_Eloqua@2026', 'user', 1, NOW()),
('sharon', 'moore', 'sharon.moore6@hotmail.com', 'User', 'Eloqua', 'United States', '$2a$12$placeholder_hash_for_Eloqua@2026', 'user', 1, NOW()),
('barbara', 'hernandez', 'barbara.hernandez47@hotmail.com', 'User', 'HubSpot', 'United States', '$2a$12$placeholder_hash_for_HubSpot@2026', 'user', 1, NOW()),
('deborah', 'taylor', 'deborah.taylor64@gmail.com', 'User', 'HubSpot', 'United States', '$2a$12$placeholder_hash_for_HubSpot@2026', 'user', 1, NOW()),
('dorothy', 'wilson', 'dorothy.wilson31@outlook.com', 'User', 'Infusionsoft', 'United States', '$2a$12$placeholder_hash_for_Infusionsoft@2026', 'user', 1, NOW()),
('michelle', 'robinson', 'michelle.robinson2@outlook.com', 'User', 'Infusionsoft', 'United States', '$2a$12$placeholder_hash_for_Infusionsoft@2026', 'user', 1, NOW()),
('sarah', 'miller', 'sarah.miller53@gmail.com', 'User', 'Infusionsoft', 'United States', '$2a$12$placeholder_hash_for_Infusionsoft@2026', 'user', 1, NOW()),
('thomas', 'perez', 'thomas.perez21@outlook.com', 'User', 'Infusionsoft', 'United States', '$2a$12$placeholder_hash_for_Infusionsoft@2026', 'user', 1, NOW()),
('elizabeth', 'perez', 'elizabeth.perez55@gmail.com', 'User', 'Insightly', 'United States', '$2a$12$placeholder_hash_for_Insightly@2026', 'user', 1, NOW()),
('emily', 'lopez', 'emily.lopez23@yahoo.com', 'User', 'Insightly', 'United States', '$2a$12$placeholder_hash_for_Insightly@2026', 'user', 1, NOW()),
('kimberly', 'jones', 'kimberly.jones43@company.com', 'User', 'Insightly', 'United States', '$2a$12$placeholder_hash_for_Insightly@2026', 'user', 1, NOW()),
('lisa', 'davis', 'lisa.davis52@company.com', 'User', 'Insightly', 'United States', '$2a$12$placeholder_hash_for_Insightly@2026', 'user', 1, NOW()),
('nancy', 'ramirez', 'nancy.ramirez41@hotmail.com', 'User', 'Insightly', 'United States', '$2a$12$placeholder_hash_for_Insightly@2026', 'user', 1, NOW()),
('patricia', 'martin', 'patricia.martin39@outlook.com', 'User', 'Insightly', 'United States', '$2a$12$placeholder_hash_for_Insightly@2026', 'user', 1, NOW()),
('charles', 'miller', 'charles.miller36@outlook.com', 'User', 'Lattice Engines', 'United States', '$2a$12$placeholder_hash_for_LatticeEngines@2026', 'user', 1, NOW()),
('linda', 'white', 'linda.white4@hotmail.com', 'User', 'Lattice Engines', 'United States', '$2a$12$placeholder_hash_for_LatticeEngines@2026', 'user', 1, NOW()),
('rebecca', 'lee', 'rebecca.lee22@hotmail.com', 'User', 'Lattice Engines', 'United States', '$2a$12$placeholder_hash_for_LatticeEngines@2026', 'user', 1, NOW()),
('sandra', 'ramirez', 'sandra.ramirez38@gmail.com', 'User', 'LeadFeeder', 'United States', '$2a$12$placeholder_hash_for_LeadFeeder@2026', 'user', 1, NOW()),
('emily', 'harris', 'emily.harris44@company.com', 'User', 'LeadSquared', 'United States', '$2a$12$placeholder_hash_for_LeadSquared@2026', 'user', 1, NOW()),
('michelle', 'martin', 'michelle.martin51@hotmail.com', 'User', 'Marketo', 'United States', '$2a$12$placeholder_hash_for_Marketo@2026', 'user', 1, NOW()),
('james', 'johnson', 'james.johnson33@hotmail.com', 'User', 'Oracle Marketing Cloud', 'United States', '$2a$12$placeholder_hash_for_OracleMarketingCloud@2026', 'user', 1, NOW()),
('jennifer', 'lopez', 'jennifer.lopez67@hotmail.com', 'User', 'Oracle Marketing Cloud', 'United States', '$2a$12$placeholder_hash_for_OracleMarketingCloud@2026', 'user', 1, NOW()),
('carol', 'wilson', 'carol.wilson54@hotmail.com', 'User', 'Outreach', 'United States', '$2a$12$placeholder_hash_for_Outreach@2026', 'user', 1, NOW()),
('jennifer', 'perez', 'jennifer.perez12@hotmail.com', 'User', 'Outreach', 'United States', '$2a$12$placeholder_hash_for_Outreach@2026', 'user', 1, NOW()),
('sandra', 'thompson', 'sandra.thompson63@gmail.com', 'User', 'Outreach', 'United States', '$2a$12$placeholder_hash_for_Outreach@2026', 'user', 1, NOW()),
('sarah', 'lee', 'sarah.lee73@company.com', 'User', 'Outreach', 'United States', '$2a$12$placeholder_hash_for_Outreach@2026', 'user', 1, NOW()),
('william', 'moore', 'william.moore14@yahoo.com', 'User', 'Outreach', 'United States', '$2a$12$placeholder_hash_for_Outreach@2026', 'user', 1, NOW()),
('lisa', 'lee', 'lisa.lee11@hotmail.com', 'User', 'RingCentral', 'United States', '$2a$12$placeholder_hash_for_RingCentral@2026', 'user', 1, NOW()),
('dorothy', 'sanchez', 'dorothy.sanchez66@company.com', 'User', 'Salesforce', 'United States', '$2a$12$placeholder_hash_for_Salesforce@2026', 'user', 1, NOW()),
('kimberly', 'taylor', 'kimberly.taylor71@company.com', 'User', 'Salesforce', 'United States', '$2a$12$placeholder_hash_for_Salesforce@2026', 'user', 1, NOW()),
('mary', 'lopez', 'mary.lopez34@company.com', 'User', 'Salesforce', 'United States', '$2a$12$placeholder_hash_for_Salesforce@2026', 'user', 1, NOW()),
('michael', 'wilson', 'michael.wilson30@company.com', 'User', 'Salesforce', 'United States', '$2a$12$placeholder_hash_for_Salesforce@2026', 'user', 1, NOW()),
('emily', 'robinson', 'emily.robinson5@outlook.com', 'User', 'Salesfusion', 'United States', '$2a$12$placeholder_hash_for_Salesfusion@2026', 'user', 1, NOW()),
('margaret', 'garcia', 'margaret.garcia10@yahoo.com', 'User', 'Salesfusion', 'United States', '$2a$12$placeholder_hash_for_Salesfusion@2026', 'user', 1, NOW()),
('rebecca', 'rodriguez', 'rebecca.rodriguez32@company.com', 'User', 'Salesfusion', 'United States', '$2a$12$placeholder_hash_for_Salesfusion@2026', 'user', 1, NOW()),
('charles', 'wilson', 'charles.wilson61@outlook.com', 'User', 'SharpSpring', 'United States', '$2a$12$placeholder_hash_for_SharpSpring@2026', 'user', 1, NOW()),
('james', 'johnson', 'james.johnson65@company.com', 'User', 'SharpSpring', 'United States', '$2a$12$placeholder_hash_for_SharpSpring@2026', 'user', 1, NOW()),
('amanda', 'gonzalez', 'amanda.gonzalez18@company.com', 'User', 'Terminus', 'United States', '$2a$12$placeholder_hash_for_Terminus@2026', 'user', 1, NOW()),
('nancy', 'lewis', 'nancy.lewis57@yahoo.com', 'User', 'Zoho', 'United States', '$2a$12$placeholder_hash_for_Zoho@2026', 'user', 1, NOW()),
('william', 'martin', 'william.martin58@outlook.com', 'User', 'Zoho', 'United States', '$2a$12$placeholder_hash_for_Zoho@2026', 'user', 1, NOW()),
('dorothy', 'garcia', 'dorothy.garcia62@outlook.com', 'User', 'ZoomInfo', 'United States', '$2a$12$placeholder_hash_for_ZoomInfo@2026', 'user', 1, NOW()),
('linda', 'miller', 'linda.miller13@outlook.com', 'User', 'ZoomInfo', 'United States', '$2a$12$placeholder_hash_for_ZoomInfo@2026', 'user', 1, NOW());