-- SQL Query to insert 500 users
-- Default Password for all accounts: User@2026
-- Bcrypt Hash (12 rounds): $2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG

INSERT INTO users (first_name, last_name, email, job_title, company_name, country, password_hash, role, is_active, failed_login_attempts, locked_until, created_at)
VALUES
('TestUser001', 'Member', 'bulk.user001@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser002', 'Member', 'bulk.user002@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser003', 'Member', 'bulk.user003@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser004', 'Member', 'bulk.user004@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser005', 'Member', 'bulk.user005@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser006', 'Member', 'bulk.user006@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser007', 'Member', 'bulk.user007@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser008', 'Member', 'bulk.user008@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser009', 'Member', 'bulk.user009@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser010', 'Member', 'bulk.user010@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser011', 'Member', 'bulk.user011@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser012', 'Member', 'bulk.user012@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser013', 'Member', 'bulk.user013@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser014', 'Member', 'bulk.user014@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser015', 'Member', 'bulk.user015@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser016', 'Member', 'bulk.user016@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser017', 'Member', 'bulk.user017@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser018', 'Member', 'bulk.user018@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser019', 'Member', 'bulk.user019@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser020', 'Member', 'bulk.user020@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser021', 'Member', 'bulk.user021@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser022', 'Member', 'bulk.user022@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser023', 'Member', 'bulk.user023@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser024', 'Member', 'bulk.user024@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser025', 'Member', 'bulk.user025@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser026', 'Member', 'bulk.user026@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser027', 'Member', 'bulk.user027@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser028', 'Member', 'bulk.user028@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser029', 'Member', 'bulk.user029@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser030', 'Member', 'bulk.user030@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser031', 'Member', 'bulk.user031@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser032', 'Member', 'bulk.user032@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser033', 'Member', 'bulk.user033@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser034', 'Member', 'bulk.user034@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser035', 'Member', 'bulk.user035@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser036', 'Member', 'bulk.user036@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser037', 'Member', 'bulk.user037@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser038', 'Member', 'bulk.user038@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser039', 'Member', 'bulk.user039@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser040', 'Member', 'bulk.user040@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser041', 'Member', 'bulk.user041@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser042', 'Member', 'bulk.user042@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser043', 'Member', 'bulk.user043@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser044', 'Member', 'bulk.user044@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser045', 'Member', 'bulk.user045@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser046', 'Member', 'bulk.user046@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser047', 'Member', 'bulk.user047@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser048', 'Member', 'bulk.user048@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser049', 'Member', 'bulk.user049@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser050', 'Member', 'bulk.user050@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser051', 'Member', 'bulk.user051@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser052', 'Member', 'bulk.user052@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser053', 'Member', 'bulk.user053@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser054', 'Member', 'bulk.user054@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser055', 'Member', 'bulk.user055@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser056', 'Member', 'bulk.user056@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser057', 'Member', 'bulk.user057@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser058', 'Member', 'bulk.user058@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser059', 'Member', 'bulk.user059@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser060', 'Member', 'bulk.user060@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser061', 'Member', 'bulk.user061@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser062', 'Member', 'bulk.user062@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser063', 'Member', 'bulk.user063@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser064', 'Member', 'bulk.user064@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser065', 'Member', 'bulk.user065@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser066', 'Member', 'bulk.user066@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser067', 'Member', 'bulk.user067@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser068', 'Member', 'bulk.user068@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser069', 'Member', 'bulk.user069@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser070', 'Member', 'bulk.user070@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser071', 'Member', 'bulk.user071@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser072', 'Member', 'bulk.user072@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser073', 'Member', 'bulk.user073@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser074', 'Member', 'bulk.user074@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser075', 'Member', 'bulk.user075@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser076', 'Member', 'bulk.user076@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser077', 'Member', 'bulk.user077@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser078', 'Member', 'bulk.user078@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser079', 'Member', 'bulk.user079@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser080', 'Member', 'bulk.user080@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser081', 'Member', 'bulk.user081@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser082', 'Member', 'bulk.user082@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser083', 'Member', 'bulk.user083@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser084', 'Member', 'bulk.user084@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser085', 'Member', 'bulk.user085@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser086', 'Member', 'bulk.user086@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser087', 'Member', 'bulk.user087@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser088', 'Member', 'bulk.user088@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser089', 'Member', 'bulk.user089@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser090', 'Member', 'bulk.user090@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser091', 'Member', 'bulk.user091@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser092', 'Member', 'bulk.user092@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser093', 'Member', 'bulk.user093@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser094', 'Member', 'bulk.user094@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser095', 'Member', 'bulk.user095@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser096', 'Member', 'bulk.user096@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser097', 'Member', 'bulk.user097@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser098', 'Member', 'bulk.user098@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser099', 'Member', 'bulk.user099@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser100', 'Member', 'bulk.user100@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser101', 'Member', 'bulk.user101@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser102', 'Member', 'bulk.user102@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser103', 'Member', 'bulk.user103@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser104', 'Member', 'bulk.user104@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser105', 'Member', 'bulk.user105@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser106', 'Member', 'bulk.user106@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser107', 'Member', 'bulk.user107@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser108', 'Member', 'bulk.user108@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser109', 'Member', 'bulk.user109@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser110', 'Member', 'bulk.user110@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser111', 'Member', 'bulk.user111@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser112', 'Member', 'bulk.user112@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser113', 'Member', 'bulk.user113@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser114', 'Member', 'bulk.user114@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser115', 'Member', 'bulk.user115@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser116', 'Member', 'bulk.user116@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser117', 'Member', 'bulk.user117@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser118', 'Member', 'bulk.user118@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser119', 'Member', 'bulk.user119@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser120', 'Member', 'bulk.user120@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser121', 'Member', 'bulk.user121@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser122', 'Member', 'bulk.user122@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser123', 'Member', 'bulk.user123@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser124', 'Member', 'bulk.user124@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser125', 'Member', 'bulk.user125@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser126', 'Member', 'bulk.user126@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser127', 'Member', 'bulk.user127@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser128', 'Member', 'bulk.user128@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser129', 'Member', 'bulk.user129@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser130', 'Member', 'bulk.user130@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser131', 'Member', 'bulk.user131@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser132', 'Member', 'bulk.user132@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser133', 'Member', 'bulk.user133@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser134', 'Member', 'bulk.user134@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser135', 'Member', 'bulk.user135@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser136', 'Member', 'bulk.user136@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser137', 'Member', 'bulk.user137@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser138', 'Member', 'bulk.user138@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser139', 'Member', 'bulk.user139@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser140', 'Member', 'bulk.user140@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser141', 'Member', 'bulk.user141@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser142', 'Member', 'bulk.user142@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser143', 'Member', 'bulk.user143@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser144', 'Member', 'bulk.user144@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser145', 'Member', 'bulk.user145@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser146', 'Member', 'bulk.user146@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser147', 'Member', 'bulk.user147@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser148', 'Member', 'bulk.user148@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser149', 'Member', 'bulk.user149@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser150', 'Member', 'bulk.user150@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser151', 'Member', 'bulk.user151@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser152', 'Member', 'bulk.user152@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser153', 'Member', 'bulk.user153@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser154', 'Member', 'bulk.user154@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser155', 'Member', 'bulk.user155@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser156', 'Member', 'bulk.user156@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser157', 'Member', 'bulk.user157@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser158', 'Member', 'bulk.user158@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser159', 'Member', 'bulk.user159@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser160', 'Member', 'bulk.user160@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser161', 'Member', 'bulk.user161@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser162', 'Member', 'bulk.user162@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser163', 'Member', 'bulk.user163@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser164', 'Member', 'bulk.user164@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser165', 'Member', 'bulk.user165@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser166', 'Member', 'bulk.user166@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser167', 'Member', 'bulk.user167@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser168', 'Member', 'bulk.user168@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser169', 'Member', 'bulk.user169@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser170', 'Member', 'bulk.user170@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser171', 'Member', 'bulk.user171@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser172', 'Member', 'bulk.user172@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser173', 'Member', 'bulk.user173@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser174', 'Member', 'bulk.user174@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser175', 'Member', 'bulk.user175@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser176', 'Member', 'bulk.user176@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser177', 'Member', 'bulk.user177@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser178', 'Member', 'bulk.user178@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser179', 'Member', 'bulk.user179@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser180', 'Member', 'bulk.user180@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser181', 'Member', 'bulk.user181@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser182', 'Member', 'bulk.user182@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser183', 'Member', 'bulk.user183@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser184', 'Member', 'bulk.user184@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser185', 'Member', 'bulk.user185@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser186', 'Member', 'bulk.user186@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser187', 'Member', 'bulk.user187@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser188', 'Member', 'bulk.user188@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser189', 'Member', 'bulk.user189@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser190', 'Member', 'bulk.user190@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser191', 'Member', 'bulk.user191@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser192', 'Member', 'bulk.user192@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser193', 'Member', 'bulk.user193@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser194', 'Member', 'bulk.user194@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser195', 'Member', 'bulk.user195@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser196', 'Member', 'bulk.user196@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser197', 'Member', 'bulk.user197@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser198', 'Member', 'bulk.user198@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser199', 'Member', 'bulk.user199@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser200', 'Member', 'bulk.user200@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser201', 'Member', 'bulk.user201@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser202', 'Member', 'bulk.user202@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser203', 'Member', 'bulk.user203@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser204', 'Member', 'bulk.user204@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser205', 'Member', 'bulk.user205@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser206', 'Member', 'bulk.user206@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser207', 'Member', 'bulk.user207@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser208', 'Member', 'bulk.user208@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser209', 'Member', 'bulk.user209@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser210', 'Member', 'bulk.user210@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser211', 'Member', 'bulk.user211@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser212', 'Member', 'bulk.user212@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser213', 'Member', 'bulk.user213@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser214', 'Member', 'bulk.user214@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser215', 'Member', 'bulk.user215@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser216', 'Member', 'bulk.user216@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser217', 'Member', 'bulk.user217@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser218', 'Member', 'bulk.user218@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser219', 'Member', 'bulk.user219@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser220', 'Member', 'bulk.user220@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser221', 'Member', 'bulk.user221@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser222', 'Member', 'bulk.user222@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser223', 'Member', 'bulk.user223@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser224', 'Member', 'bulk.user224@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser225', 'Member', 'bulk.user225@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser226', 'Member', 'bulk.user226@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser227', 'Member', 'bulk.user227@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser228', 'Member', 'bulk.user228@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser229', 'Member', 'bulk.user229@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser230', 'Member', 'bulk.user230@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser231', 'Member', 'bulk.user231@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser232', 'Member', 'bulk.user232@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser233', 'Member', 'bulk.user233@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser234', 'Member', 'bulk.user234@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser235', 'Member', 'bulk.user235@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser236', 'Member', 'bulk.user236@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser237', 'Member', 'bulk.user237@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser238', 'Member', 'bulk.user238@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser239', 'Member', 'bulk.user239@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser240', 'Member', 'bulk.user240@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser241', 'Member', 'bulk.user241@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser242', 'Member', 'bulk.user242@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser243', 'Member', 'bulk.user243@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser244', 'Member', 'bulk.user244@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser245', 'Member', 'bulk.user245@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser246', 'Member', 'bulk.user246@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser247', 'Member', 'bulk.user247@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser248', 'Member', 'bulk.user248@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser249', 'Member', 'bulk.user249@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser250', 'Member', 'bulk.user250@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser251', 'Member', 'bulk.user251@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser252', 'Member', 'bulk.user252@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser253', 'Member', 'bulk.user253@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser254', 'Member', 'bulk.user254@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser255', 'Member', 'bulk.user255@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser256', 'Member', 'bulk.user256@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser257', 'Member', 'bulk.user257@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser258', 'Member', 'bulk.user258@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser259', 'Member', 'bulk.user259@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser260', 'Member', 'bulk.user260@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser261', 'Member', 'bulk.user261@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser262', 'Member', 'bulk.user262@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser263', 'Member', 'bulk.user263@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser264', 'Member', 'bulk.user264@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser265', 'Member', 'bulk.user265@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser266', 'Member', 'bulk.user266@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser267', 'Member', 'bulk.user267@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser268', 'Member', 'bulk.user268@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser269', 'Member', 'bulk.user269@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser270', 'Member', 'bulk.user270@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser271', 'Member', 'bulk.user271@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser272', 'Member', 'bulk.user272@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser273', 'Member', 'bulk.user273@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser274', 'Member', 'bulk.user274@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser275', 'Member', 'bulk.user275@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser276', 'Member', 'bulk.user276@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser277', 'Member', 'bulk.user277@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser278', 'Member', 'bulk.user278@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser279', 'Member', 'bulk.user279@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser280', 'Member', 'bulk.user280@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser281', 'Member', 'bulk.user281@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser282', 'Member', 'bulk.user282@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser283', 'Member', 'bulk.user283@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser284', 'Member', 'bulk.user284@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser285', 'Member', 'bulk.user285@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser286', 'Member', 'bulk.user286@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser287', 'Member', 'bulk.user287@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser288', 'Member', 'bulk.user288@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser289', 'Member', 'bulk.user289@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser290', 'Member', 'bulk.user290@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser291', 'Member', 'bulk.user291@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser292', 'Member', 'bulk.user292@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser293', 'Member', 'bulk.user293@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser294', 'Member', 'bulk.user294@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser295', 'Member', 'bulk.user295@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser296', 'Member', 'bulk.user296@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser297', 'Member', 'bulk.user297@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser298', 'Member', 'bulk.user298@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser299', 'Member', 'bulk.user299@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser300', 'Member', 'bulk.user300@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser301', 'Member', 'bulk.user301@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser302', 'Member', 'bulk.user302@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser303', 'Member', 'bulk.user303@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser304', 'Member', 'bulk.user304@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser305', 'Member', 'bulk.user305@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser306', 'Member', 'bulk.user306@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser307', 'Member', 'bulk.user307@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser308', 'Member', 'bulk.user308@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser309', 'Member', 'bulk.user309@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser310', 'Member', 'bulk.user310@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser311', 'Member', 'bulk.user311@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser312', 'Member', 'bulk.user312@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser313', 'Member', 'bulk.user313@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser314', 'Member', 'bulk.user314@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser315', 'Member', 'bulk.user315@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser316', 'Member', 'bulk.user316@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser317', 'Member', 'bulk.user317@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser318', 'Member', 'bulk.user318@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser319', 'Member', 'bulk.user319@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser320', 'Member', 'bulk.user320@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser321', 'Member', 'bulk.user321@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser322', 'Member', 'bulk.user322@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser323', 'Member', 'bulk.user323@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser324', 'Member', 'bulk.user324@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser325', 'Member', 'bulk.user325@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser326', 'Member', 'bulk.user326@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser327', 'Member', 'bulk.user327@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser328', 'Member', 'bulk.user328@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser329', 'Member', 'bulk.user329@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser330', 'Member', 'bulk.user330@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser331', 'Member', 'bulk.user331@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser332', 'Member', 'bulk.user332@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser333', 'Member', 'bulk.user333@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser334', 'Member', 'bulk.user334@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser335', 'Member', 'bulk.user335@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser336', 'Member', 'bulk.user336@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser337', 'Member', 'bulk.user337@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser338', 'Member', 'bulk.user338@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser339', 'Member', 'bulk.user339@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser340', 'Member', 'bulk.user340@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser341', 'Member', 'bulk.user341@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser342', 'Member', 'bulk.user342@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser343', 'Member', 'bulk.user343@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser344', 'Member', 'bulk.user344@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser345', 'Member', 'bulk.user345@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser346', 'Member', 'bulk.user346@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser347', 'Member', 'bulk.user347@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser348', 'Member', 'bulk.user348@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser349', 'Member', 'bulk.user349@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser350', 'Member', 'bulk.user350@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser351', 'Member', 'bulk.user351@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser352', 'Member', 'bulk.user352@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser353', 'Member', 'bulk.user353@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser354', 'Member', 'bulk.user354@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser355', 'Member', 'bulk.user355@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser356', 'Member', 'bulk.user356@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser357', 'Member', 'bulk.user357@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser358', 'Member', 'bulk.user358@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser359', 'Member', 'bulk.user359@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser360', 'Member', 'bulk.user360@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser361', 'Member', 'bulk.user361@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser362', 'Member', 'bulk.user362@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser363', 'Member', 'bulk.user363@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser364', 'Member', 'bulk.user364@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser365', 'Member', 'bulk.user365@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser366', 'Member', 'bulk.user366@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser367', 'Member', 'bulk.user367@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser368', 'Member', 'bulk.user368@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser369', 'Member', 'bulk.user369@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser370', 'Member', 'bulk.user370@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser371', 'Member', 'bulk.user371@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser372', 'Member', 'bulk.user372@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser373', 'Member', 'bulk.user373@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser374', 'Member', 'bulk.user374@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser375', 'Member', 'bulk.user375@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser376', 'Member', 'bulk.user376@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser377', 'Member', 'bulk.user377@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser378', 'Member', 'bulk.user378@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser379', 'Member', 'bulk.user379@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser380', 'Member', 'bulk.user380@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser381', 'Member', 'bulk.user381@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser382', 'Member', 'bulk.user382@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser383', 'Member', 'bulk.user383@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser384', 'Member', 'bulk.user384@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser385', 'Member', 'bulk.user385@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser386', 'Member', 'bulk.user386@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser387', 'Member', 'bulk.user387@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser388', 'Member', 'bulk.user388@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser389', 'Member', 'bulk.user389@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser390', 'Member', 'bulk.user390@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser391', 'Member', 'bulk.user391@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser392', 'Member', 'bulk.user392@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser393', 'Member', 'bulk.user393@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser394', 'Member', 'bulk.user394@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser395', 'Member', 'bulk.user395@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser396', 'Member', 'bulk.user396@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser397', 'Member', 'bulk.user397@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser398', 'Member', 'bulk.user398@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser399', 'Member', 'bulk.user399@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser400', 'Member', 'bulk.user400@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser401', 'Member', 'bulk.user401@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser402', 'Member', 'bulk.user402@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser403', 'Member', 'bulk.user403@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser404', 'Member', 'bulk.user404@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser405', 'Member', 'bulk.user405@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser406', 'Member', 'bulk.user406@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser407', 'Member', 'bulk.user407@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser408', 'Member', 'bulk.user408@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser409', 'Member', 'bulk.user409@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser410', 'Member', 'bulk.user410@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser411', 'Member', 'bulk.user411@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser412', 'Member', 'bulk.user412@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser413', 'Member', 'bulk.user413@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser414', 'Member', 'bulk.user414@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser415', 'Member', 'bulk.user415@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser416', 'Member', 'bulk.user416@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser417', 'Member', 'bulk.user417@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser418', 'Member', 'bulk.user418@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser419', 'Member', 'bulk.user419@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser420', 'Member', 'bulk.user420@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser421', 'Member', 'bulk.user421@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser422', 'Member', 'bulk.user422@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser423', 'Member', 'bulk.user423@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser424', 'Member', 'bulk.user424@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser425', 'Member', 'bulk.user425@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser426', 'Member', 'bulk.user426@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser427', 'Member', 'bulk.user427@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser428', 'Member', 'bulk.user428@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser429', 'Member', 'bulk.user429@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser430', 'Member', 'bulk.user430@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser431', 'Member', 'bulk.user431@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser432', 'Member', 'bulk.user432@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser433', 'Member', 'bulk.user433@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser434', 'Member', 'bulk.user434@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser435', 'Member', 'bulk.user435@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser436', 'Member', 'bulk.user436@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser437', 'Member', 'bulk.user437@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser438', 'Member', 'bulk.user438@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser439', 'Member', 'bulk.user439@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser440', 'Member', 'bulk.user440@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser441', 'Member', 'bulk.user441@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser442', 'Member', 'bulk.user442@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser443', 'Member', 'bulk.user443@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser444', 'Member', 'bulk.user444@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser445', 'Member', 'bulk.user445@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser446', 'Member', 'bulk.user446@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser447', 'Member', 'bulk.user447@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser448', 'Member', 'bulk.user448@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser449', 'Member', 'bulk.user449@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser450', 'Member', 'bulk.user450@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser451', 'Member', 'bulk.user451@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser452', 'Member', 'bulk.user452@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser453', 'Member', 'bulk.user453@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser454', 'Member', 'bulk.user454@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser455', 'Member', 'bulk.user455@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser456', 'Member', 'bulk.user456@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser457', 'Member', 'bulk.user457@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser458', 'Member', 'bulk.user458@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser459', 'Member', 'bulk.user459@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser460', 'Member', 'bulk.user460@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser461', 'Member', 'bulk.user461@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser462', 'Member', 'bulk.user462@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser463', 'Member', 'bulk.user463@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser464', 'Member', 'bulk.user464@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser465', 'Member', 'bulk.user465@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser466', 'Member', 'bulk.user466@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser467', 'Member', 'bulk.user467@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser468', 'Member', 'bulk.user468@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser469', 'Member', 'bulk.user469@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser470', 'Member', 'bulk.user470@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser471', 'Member', 'bulk.user471@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser472', 'Member', 'bulk.user472@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser473', 'Member', 'bulk.user473@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser474', 'Member', 'bulk.user474@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser475', 'Member', 'bulk.user475@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser476', 'Member', 'bulk.user476@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser477', 'Member', 'bulk.user477@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser478', 'Member', 'bulk.user478@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser479', 'Member', 'bulk.user479@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser480', 'Member', 'bulk.user480@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser481', 'Member', 'bulk.user481@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser482', 'Member', 'bulk.user482@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser483', 'Member', 'bulk.user483@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser484', 'Member', 'bulk.user484@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser485', 'Member', 'bulk.user485@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser486', 'Member', 'bulk.user486@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser487', 'Member', 'bulk.user487@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser488', 'Member', 'bulk.user488@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser489', 'Member', 'bulk.user489@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser490', 'Member', 'bulk.user490@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser491', 'Member', 'bulk.user491@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser492', 'Member', 'bulk.user492@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser493', 'Member', 'bulk.user493@tgstest.com', 'Analyst', 'FinPulse', 'Germany', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser494', 'Member', 'bulk.user494@tgstest.com', 'Analyst', 'CyberShield', 'France', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser495', 'Member', 'bulk.user495@tgstest.com', 'Analyst', 'AlphaDigital', 'Singapore', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser496', 'Member', 'bulk.user496@tgstest.com', 'Analyst', 'TechCorp', 'India', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser497', 'Member', 'bulk.user497@tgstest.com', 'Analyst', 'Innovatech', 'United States', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser498', 'Member', 'bulk.user498@tgstest.com', 'Analyst', 'CloudScale', 'United Kingdom', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser499', 'Member', 'bulk.user499@tgstest.com', 'Analyst', 'GlobalData', 'Australia', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW()),
('TestUser500', 'Member', 'bulk.user500@tgstest.com', 'Analyst', 'EnterpriseAI', 'Canada', '$2b$12$hwJMd0Dah4ybPY3Yl1cCTeVdt/oyyizrjSuoxsT7wb8BevtCA8hCG', 'user', 1, 0, NULL, NOW());
